# Generated by Django 5.2.11 on 2026-03-19 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0010_customer_addr_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('email', '📧 Email'), ('call', '📞 Дзвінок'), ('pause', '⏸ Пауза'), ('decision', '🔀 Рішення')], default='email', max_length=20, verbose_name='Тип кроку')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Деталі')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Заплановано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Виконано')),
                ('outcome', models.CharField(choices=[('pending', '⏳ Очікує'), ('done_pos', '✅ Виконано (+)'), ('done_neg', '⚠️ Виконано (−)'), ('skipped', '⏭ Пропущено'), ('no_response', '🔇 Немає відповіді')], default='pending', max_length=20, verbose_name='Результат')),
                ('outcome_notes', models.TextField(blank=True, default='', verbose_name='Примітки до результату')),
            ],
            options={
                'verbose_name': 'Крок клієнта',
                'verbose_name_plural': 'Кроки клієнта',
                'ordering': ['strategy', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('behavior_type', models.CharField(choices=[('reactivation', 'Реактивація (At Risk / Lost)'), ('nurturing', 'Нарощування (Promising)'), ('retention', 'Утримання VIP (Champion)'), ('onboarding', 'Онбординг (нові клієнти)')], default='nurturing', max_length=20, verbose_name='Тип поведінки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Шаблон стратегії',
                'verbose_name_plural': 'Шаблони стратегій',
                'ordering': ['behavior_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Назва стратегії')),
                ('status', models.CharField(choices=[('active', '⚡ Активна'), ('paused', '⏸ Призупинена'), ('done', '✅ Завершена'), ('failed', '❌ Провалена')], default='active', max_length=10, verbose_name='Статус')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Розпочато')),
                ('next_action_at', models.DateTimeField(blank=True, null=True, verbose_name='Наступна дія')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Нотатки')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategy.customerstep', verbose_name='Поточний крок')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='crm.customer', verbose_name='Клієнт')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_strategies', to='strategy.strategytemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Стратегія клієнта',
                'verbose_name_plural': 'Стратегії клієнтів',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='customerstep',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='strategy.customerstrategy', verbose_name='Стратегія'),
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('pending', '⏳ Очікує'), ('done_pos', '✅ Виконано (+)'), ('done_neg', '⚠️ Виконано (−)'), ('skipped', '⏭ Пропущено'), ('no_response', '🔇 Немає відповіді')], default='done_pos', max_length=20, verbose_name='Результат')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примітки')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час запису')),
                ('ai_suggestion', models.TextField(blank=True, default='', help_text='Заповнюється автоматично у Фазі 2 (AI-радник)', verbose_name='AI-підказка')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='strategy.customerstep', verbose_name='Крок')),
            ],
            options={
                'verbose_name': 'Лог кроку',
                'verbose_name_plural': 'Лог кроків',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('email', '📧 Email'), ('call', '📞 Дзвінок'), ('pause', '⏸ Пауза'), ('decision', '🔀 Рішення')], default='email', max_length=20, verbose_name='Тип кроку')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Деталі / скрипт')),
                ('delay_days', models.PositiveSmallIntegerField(default=0, help_text='0 = виконати одразу після попереднього кроку', verbose_name='Затримка (днів)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('canvas_x', models.FloatField(default=0.0, verbose_name='Canvas X')),
                ('canvas_y', models.FloatField(default=0.0, verbose_name='Canvas Y')),
                ('next_step_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_no_from', to='strategy.templatestep', verbose_name='Наступний (Ні / негатив)')),
                ('next_step_yes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_yes_from', to='strategy.templatestep', verbose_name='Наступний (Так / позитив)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='strategy.strategytemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Крок шаблону',
                'verbose_name_plural': 'Кроки шаблону',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='customerstep',
            name='template_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.templatestep', verbose_name='Крок шаблону'),
        ),
    ]
