# Generated by Django 5.2.11 on 2026-04-03 07:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='sk-ant-... з console.anthropic.com', max_length=200, verbose_name='Anthropic API Key')),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Отримати у @BotFather', max_length=100, verbose_name='Telegram Bot Token')),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, verbose_name='Місячний бюджет ($)')),
                ('alert_threshold_usd', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Надіслати алерт коли витрачено більше цієї суми', max_digits=8, verbose_name='Поріг сповіщення ($)')),
                ('budget_alert_telegram_id', models.CharField(blank=True, help_text='Твій особистий Telegram ID (дізнатись через /myid в боті)', max_length=50, verbose_name='Telegram ID для бюджетних алертів')),
                ('per_user_daily_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=6, verbose_name='Денний ліміт на юзера ($)')),
                ('persona_name', models.CharField(default='Minerva', max_length=50, verbose_name="Ім'я персонажа")),
                ('persona_base_prompt', models.TextField(default='Ти — Мінерва, богиня мудрості, що живе в серці системи Minerva ERP.\nТи говориш від імені жінки — мудрої, трохи величної, але з почуттям гумору.\nТи НІКОЛИ не кажеш що ти Claude або AI від Anthropic.\nТи НІКОЛИ не вигадуєш дані — завжди використовуєш інструменти.', verbose_name='Базовий промпт персонажа')),
                ('ai_allow_email_sending', models.BooleanField(default=True, verbose_name='Дозволити AI відправляти email')),
                ('ai_allow_order_creation', models.BooleanField(default=False, verbose_name='Дозволити AI створювати замовлення')),
                ('ai_allow_inventory_edit', models.BooleanField(default=False, verbose_name='Дозволити AI редагувати склад')),
                ('ai_allow_financial_data', models.BooleanField(default=True, verbose_name='Дозволити AI бачити фінансові дані')),
            ],
            options={
                'verbose_name': 'Налаштування AI',
                'verbose_name_plural': 'Налаштування AI',
            },
        ),
    ]
