# Generated by Django 5.2.11 on 2026-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_strategytemplate_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='enable_web_search',
            field=models.BooleanField(default=True, help_text='Мінерва шукає інформацію про компанію клієнта в інтернеті під час аналізу. Робить аналіз точнішим для B2B клієнтів. Вимкни щоб зменшити витрати токенів (~$0.02 за аналіз).', verbose_name='Web Search для аналізу клієнтів'),
        ),
    ]
