# Generated by Django 5.2.11 on 2026-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_aisettings_enable_web_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='enable_web_search_chat',
            field=models.BooleanField(default=False, help_text='Мінерва шукає в інтернеті під час звичайних розмов у WebChat і Telegram. Вмикай лише якщо потрібні актуальні дані (курси, новини тощо). Збільшує витрати токенів для кожного запиту (~$0.01–0.05 за повідомлення).', verbose_name='Web Search для WebChat та Telegram бота'),
        ),
    ]
