# Generated by Django 5.2.11 on 2026-02-19 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='schedule_cron',
            field=models.CharField(blank=True, default='0 */6 * * *', help_text='Формат: хвилина година день місяць день_тижня. Приклад: 0 */6 * * * (кожні 6 год)', max_length=100, validators=[django.core.validators.RegexValidator(message='Неправильний формат cron', regex='^[\\d\\*\\/\\-\\,\\s]+$')], verbose_name='Розклад (cron)'),
        ),
    ]
