# Generated by Django 5.2.11 on 2026-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_digikeyconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digikeyconfig',
            name='webhook_url_note',
            field=models.CharField(blank=True, default='', help_text='Публічний URL куди DigiKey надсилатиме POST. Приклад: https://akustik.synology.me:81/bots/digikey/webhook/', max_length=300, verbose_name='Webhook URL (нотатка)'),
        ),
    ]
