# Generated by Django 5.2.11 on 2026-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_digikeyconfig_webhook_url_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeyconfig',
            name='marketplace_access_token',
            field=models.TextField(blank=True, default='', verbose_name='Marketplace Access Token'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='marketplace_refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='Marketplace Refresh Token'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='marketplace_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Marketplace Token дійсний до'),
        ),
    ]
