# Generated by Django 5.2.11 on 2026-04-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_digikeyconfig_auto_confirm_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digikeyconfig',
            name='webhook_url_note',
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='public_base_url',
            field=models.CharField(blank=True, default='', help_text='Базовий URL без слеша на кінці. Приклад: https://akustik.synology.me:81 — використовується для OAuth Callback та Webhook URL.', max_length=200, verbose_name='Публічний URL сайту'),
        ),
        migrations.AlterField(
            model_name='digikeyconfig',
            name='webhook_enabled',
            field=models.BooleanField(default=False, verbose_name='Webhook увімкнений'),
        ),
        migrations.AlterField(
            model_name='digikeyconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', help_text='Довільний рядок — вкажи той самий і в DigiKey dev portal → Webhooks', max_length=200, verbose_name='Webhook Secret'),
        ),
    ]
