# Generated by Django 5.2.11 on 2026-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_digikeyconfig_sync_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeyconfig',
            name='supplier_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='supplier_country',
            field=models.CharField(blank=True, default='', help_text='Напр. DE / US / UA', max_length=2, verbose_name='Країна (ISO 2)'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='supplier_name',
            field=models.CharField(blank=True, default='', help_text='Відображається у верхньому лівому куті Pack List', max_length=200, verbose_name='Назва компанії'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='supplier_state',
            field=models.CharField(blank=True, default='', help_text="Необов'язково. Напр. Bavaria", max_length=100, verbose_name='Штат / регіон'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='supplier_street',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Вулиця, будинок'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='supplier_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Поштовий індекс'),
        ),
    ]
