# Generated by Django 5.2.11 on 2026-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_digikeyconfig_supplier_id_digikeylisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeylisting',
            name='dk_lifecycle_code',
            field=models.CharField(blank=True, default='', help_text='Код атрибута "Product Life Cycle Status" з DigiKey Custom Fields API', max_length=20, verbose_name='Lifecycle attr code'),
        ),
        migrations.AddField(
            model_name='digikeylisting',
            name='dk_lifecycle_status',
            field=models.CharField(blank=True, default='Active', help_text='напр. "Active", "Obsolete", "Last Time Buy". Обов\'язково для DigiKey PIM. Код атрибута — знайди через кнопку 📋 Custom Fields.', max_length=100, verbose_name='Product Life Cycle Status'),
        ),
        migrations.AddField(
            model_name='digikeylisting',
            name='dk_packaging',
            field=models.CharField(blank=True, default='', help_text='напр. "Tape & Reel (TR)", "Cut Tape (CT)", "Bulk". Обов\'язково для DigiKey PIM. Код атрибута — знайди через кнопку 📋 Custom Fields.', max_length=100, verbose_name='Packaging'),
        ),
        migrations.AddField(
            model_name='digikeylisting',
            name='dk_packaging_code',
            field=models.CharField(blank=True, default='', help_text='Код атрибута "Packaging" з DigiKey Custom Fields API (напр. "7")', max_length=20, verbose_name='Packaging attr code'),
        ),
        migrations.AlterField(
            model_name='digikeyconfig',
            name='marketplace_supplier_id',
            field=models.CharField(blank=True, default='', help_text='Числовий Vendor ID з supplier.digikey.com → Account → Company Profile (напр. 3228)', max_length=64, verbose_name='Marketplace Vendor ID'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_category_id',
            field=models.CharField(blank=True, default='', help_text='Код категорії DigiKey (напр. "29" для RF Filters). Знайти в DigiKey Marketplace Portal → Product Catalog', max_length=256, verbose_name='DK Category ID'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_datasheet_url',
            field=models.URLField(blank=True, default='', help_text='Пряме посилання на datasheet', verbose_name='Datasheet (URL)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_description',
            field=models.TextField(help_text='Повний опис товару, макс. 2048 символів', max_length=2048, verbose_name='Опис товару (DK)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_image_url',
            field=models.URLField(blank=True, default='', help_text='Пряме посилання на зображення товару', verbose_name='Фото (URL)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_lead_time_days',
            field=models.PositiveIntegerField(default=11, help_text='Кількість днів від замовлення до відправки', verbose_name='Термін відвантаження (дні)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_manufacturer',
            field=models.CharField(blank=True, default='', help_text='Назва виробника, макс. 50 символів', max_length=50, verbose_name='Виробник (DK)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Мінімальна кількість для замовлення (≥ 1)', verbose_name='MOQ (мін. кількість)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_offer_id',
            field=models.CharField(blank=True, default='', help_text='UUID — заповнюється автоматично після публікації', max_length=36, verbose_name='DK Offer ID'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_prices',
            field=models.JSONField(default=list, help_text='Список цінових тирів: [{"qty": 1, "price": 11.99}, ...]', verbose_name='Цінові тири'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_product_id',
            field=models.CharField(blank=True, default='', help_text='UUID — заповнюється автоматично після публікації', max_length=36, verbose_name='DK Product ID'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_qty_alert',
            field=models.PositiveIntegerField(default=3, help_text='При залишку нижче цього — DigiKey виводить попередження', verbose_name='Мін. залишок (алерт)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_supplier_sku',
            field=models.CharField(blank=True, default='', help_text='Порожньо = використовує SKU товару', max_length=50, verbose_name='Supplier SKU (DK)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_title',
            field=models.CharField(help_text='Назва товару на DigiKey, макс. 50 символів', max_length=50, verbose_name='Назва (DK)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_bandwidth',
            field=models.CharField(blank=True, default='', help_text='напр. "210MHz"', max_length=100, verbose_name='Bandwidth (398)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_filter_type',
            field=models.CharField(blank=True, default='', help_text='Band Pass / Band Stop / Low Pass / High Pass / Notch', max_length=100, verbose_name='Filter Type (21)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_frequency',
            field=models.CharField(blank=True, default='', help_text='напр. "1.12GHz Center"', max_length=100, verbose_name='Frequency (139)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_height_max',
            field=models.CharField(blank=True, default='', help_text='напр. "0.063\\" (1.60mm)"', max_length=100, verbose_name='Height Max (966)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_insertion_loss',
            field=models.CharField(blank=True, default='', help_text='напр. "4dB"', max_length=100, verbose_name='Insertion Loss (327)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_mounting_type',
            field=models.CharField(blank=True, default='', help_text='напр. "Free Hanging (In-Line)"', max_length=100, verbose_name='Mounting Type (69)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_package_case',
            field=models.CharField(blank=True, default='', help_text='напр. "Inline, SMA Connection, F and M"', max_length=100, verbose_name='Package / Case (16)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_ripple',
            field=models.CharField(blank=True, default='', help_text='напр. "1.6dB"', max_length=100, verbose_name='Ripple (428)'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='fa_size_dimension',
            field=models.CharField(blank=True, default='', help_text='напр. "1.496\\" L x 1.338\\" W (38mm x 34mm)"', max_length=200, verbose_name='Size / Dimension (46)'),
        ),
    ]
