# Generated by Django 5.2.11 on 2026-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_digikeylisting_packaging_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digikeylisting',
            name='dk_lifecycle_code',
        ),
        migrations.RemoveField(
            model_name='digikeylisting',
            name='dk_packaging_code',
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_lifecycle_status',
            field=models.CharField(blank=True, default='Active', help_text='Обов\'язково. Значення: Active / Obsolete / Last Time Buy / Not For New Design. Код атрибута DigiKey: "productLifecycleStatus"', max_length=100, verbose_name='Product Life Cycle Status'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='dk_packaging',
            field=models.CharField(blank=True, default='', help_text='Обов\'язково. Значення: Tape & Reel (TR) / Cut Tape (CT) / Bulk / Digi-Reel®. Код атрибута DigiKey: "packaging"', max_length=100, verbose_name='Packaging'),
        ),
    ]
