# Generated by Django 5.2.11 on 2026-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_digikeylisting_remove_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeylisting',
            name='dk_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='additionalFields з DigiKey Products API у форматі {"code": "value", ...}. Заповнюється кнопкою «📥 Стягнути поля з DigiKey».', verbose_name='Всі атрибути DigiKey'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='category_type',
            field=models.CharField(choices=[('filter', 'RF Filter'), ('antenna', 'Antenna'), ('cable', 'Cable Assembly'), ('connector', 'Connector / Adapter'), ('other', 'Інше')], default='filter', max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='digikeylisting',
            name='sync_status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('staged', '⏳ Очікує затвердження'), ('published', 'Опубліковано'), ('error', 'Помилка')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
