# Generated by Django 5.2.11 on 2026-06-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_digikeylisting_dk_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digikeylisting',
            name='category_type',
            field=models.CharField(choices=[('filter', 'RF Filter'), ('antenna', 'Antenna'), ('cable', 'Cable Assembly'), ('connector', 'Connector / Adapter'), ('other', 'Інше')], default='other', max_length=20, verbose_name='Категорія'),
        ),
    ]
