# Generated by Django 5.2.11 on 2026-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_digikeylisting_dk_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeylisting',
            name='dk_quantity_override',
            field=models.IntegerField(blank=True, help_text='Кількість що передається на DigiKey. Якщо порожньо — використовується залишок складу. Оновлюється автоматично при «📥 Стягнути з DigiKey».', null=True, verbose_name='Кількість для DigiKey'),
        ),
    ]
