# Generated by Django 5.2.11 on 2026-06-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0017_digikeylisting_dk_quantity_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeylisting',
            name='price_delta_pct',
            field=models.FloatField(blank=True, help_text='Останній застосований масовий відсоток зміни цін (наприклад +10 або -5).', null=True, verbose_name='Остання зміна цін (%)'),
        ),
        migrations.CreateModel(
            name='DigiKeyPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Застосовано')),
                ('delta_pct', models.FloatField(verbose_name='Зміна (%)')),
                ('old_prices', models.JSONField(verbose_name='Старі ціни')),
                ('new_prices', models.JSONField(verbose_name='Нові ціни')),
                ('user', models.CharField(blank=True, default='', max_length=150, verbose_name='Користувач')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='bots.digikeylisting', verbose_name='Лістинг')),
            ],
            options={
                'verbose_name': 'Лог зміни цін',
                'verbose_name_plural': 'Лог змін цін',
                'ordering': ['-applied_at'],
            },
        ),
    ]
