# Generated by Django 5.2.11 on 2026-06-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0021_backfill_dk_price_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Проведено')),
                ('run_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Користувач')),
                ('strategy', models.CharField(blank=True, max_length=30, verbose_name='Стратегія')),
                ('strategy_name', models.CharField(blank=True, max_length=120, verbose_name='Назва стратегії')),
                ('quality_score', models.SmallIntegerField(blank=True, null=True, verbose_name='Оцінка якості')),
                ('quality_summary', models.CharField(blank=True, max_length=300, verbose_name='Резюме якості')),
                ('recommended_prices', models.JSONField(default=list, verbose_name='Рекомендовані ціни')),
                ('quality_issues', models.JSONField(default=list, verbose_name='Проблеми якості')),
                ('local_issues', models.JSONField(default=list, verbose_name='Локальні перевірки')),
                ('expected_impact', models.CharField(blank=True, max_length=300, verbose_name='Очікуваний ефект')),
                ('post_change_advice', models.CharField(blank=True, max_length=300, verbose_name='Порада після зміни')),
                ('price_change_summary', models.CharField(blank=True, max_length=200, verbose_name='Зміна цін (резюме)')),
                ('skipped_ai', models.BooleanField(default=False, verbose_name='AI не викликався')),
                ('prices_before', models.JSONField(default=list, verbose_name='Ціни на момент аналізу')),
                ('sales_snapshot', models.JSONField(default=dict, verbose_name='Знімок продажів')),
                ('prices_applied', models.BooleanField(default=False, verbose_name='Ціни застосовані')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Застосовано')),
                ('applied_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Застосував')),
                ('outcome_checked', models.BooleanField(default=False, verbose_name='Результат перевірено')),
                ('outcome_notes', models.TextField(blank=True, default='', verbose_name='Нотатки результату')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='bots.digikeylisting', verbose_name='Лістинг')),
            ],
            options={
                'verbose_name': 'AI Аналіз',
                'verbose_name_plural': 'AI Аналізи',
                'ordering': ['-run_at'],
            },
        ),
    ]
