# Generated by Django 5.2.11 on 2026-06-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_ai_analysis_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeylisting',
            name='ignored_quality_fields',
            field=models.JSONField(blank=True, default=list, help_text='Поля, для яких локальні попередження вимкнено вручну', verbose_name='Ігноровані поля перевірок'),
        ),
    ]
