# Generated by Django 5.2.11 on 2026-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0023_ignored_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeylisting',
            name='error_log',
            field=models.JSONField(blank=True, default=list, help_text='Автоматично: хронологія помилок синхронізації (макс. 20)', verbose_name='Журнал помилок'),
        ),
        migrations.AddField(
            model_name='digikeylisting',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час помилки'),
        ),
    ]
