# Generated by Django 5.2.11 on 2026-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0028_digikeyconfig_msg_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_notify_email',
            field=models.BooleanField(default=True, verbose_name='Email сповіщення'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_notify_email_to',
            field=models.CharField(blank=True, default='', help_text='Порожньо = взяти адресу з загальних налаштувань сповіщень', max_length=500, verbose_name='Email одержувачів (через кому)'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_notify_on_error',
            field=models.BooleanField(default=True, help_text='Telegram/Email якщо синк падає після всіх спроб (timeout, network error)', verbose_name="Сповіщати при збоях з'єднання"),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_notify_on_reauth',
            field=models.BooleanField(default=True, help_text='Якщо refresh_token недійсний — надіслати сповіщення з посиланням на OAuth', verbose_name='Сповіщати коли потрібна повторна авторизація'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_notify_telegram',
            field=models.BooleanField(default=True, verbose_name='Telegram сповіщення'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_notify_telegram_mode',
            field=models.CharField(choices=[('group', 'Загальний чат'), ('private', 'Приватно суперадміну')], default='group', max_length=10, verbose_name='Кому в Telegram'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_retry_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Скільки разів повторити запит перед тим як надіслати сповіщення (1–10)', verbose_name='Кількість спроб при збої'),
        ),
        migrations.AddField(
            model_name='digikeyconfig',
            name='api_retry_delay',
            field=models.PositiveSmallIntegerField(default=10, help_text='Секунди між повторними спробами підключення до DigiKey API', verbose_name='Затримка між спробами (сек)'),
        ),
        migrations.AlterField(
            model_name='digikeyconfig',
            name='msg_check_interval',
            field=models.PositiveSmallIntegerField(default=15, help_text='Рекомендовано: 5–60 хв. Використовується cron_runner (MSG_CHECK_INTERVAL).', verbose_name='Інтервал перевірки (хвилин)'),
        ),
        migrations.AlterField(
            model_name='digikeymessageseen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
