# Generated by Django 5.2.11 on 2026-06-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0032_digikeyconfig_poll_notify_fields'),
        ('inventory', '0033_rfqemailtemplate_diagram_in_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digikeylisting',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dk_listing', to='inventory.product', verbose_name='Товар'),
        ),
    ]
