# Generated by Django 5.2.11 on 2026-03-30 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50, unique=True, verbose_name='App label')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('tier', models.CharField(choices=[('core', '🔒 Базовий (завжди увімкнено)'), ('standard', '📦 Стандартний'), ('premium', '⭐ Преміум')], default='standard', max_length=10, verbose_name='Тир')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Реєстр модулів',
                'ordering': ['order', 'app_label'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', '👑 Суперадмін'), ('admin', '🔑 Адміністратор'), ('manager', '💼 Менеджер'), ('warehouse', '📦 Складник'), ('accountant', '💰 Бухгалтер'), ('ai', '🤖 AI-асистент')], default='admin', max_length=20, verbose_name='Роль')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('ai_enabled', models.BooleanField(default=False, verbose_name='AI увімкнено')),
                ('ai_model', models.CharField(default='claude-sonnet-4-6', max_length=60, verbose_name='AI модель')),
                ('ai_system_prompt', models.TextField(blank=True, verbose_name='Системний промпт')),
                ('ai_temperature', models.FloatField(default=0.7, verbose_name='Температура AI')),
                ('allowed_modules', models.JSONField(blank=True, default=list, help_text='Залиште порожнім щоб використовувати дефолти ролі', verbose_name='Дозволені модулі')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вхід'), ('logout', 'Вихід'), ('create', 'Створення'), ('update', 'Зміна'), ('delete', 'Видалення'), ('view', 'Перегляд'), ('export', 'Експорт'), ('import', 'Імпорт')], max_length=10, verbose_name='Дія')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name="ID об'єкта")),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name="Об'єкт")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Деталі')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Час')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name="Тип об'єкта")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Журнал аудиту',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx')],
            },
        ),
    ]
