# Generated by Django 5.2.11 on 2026-04-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=list, help_text='Заповнюйте лише якщо пакет не підходить. Порожній = авто', verbose_name='Ручний список модулів'),
        ),
        migrations.CreateModel(
            name='ModuleBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва пакету')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('color', models.CharField(blank=True, default='#58a6ff', help_text='HEX, напр. #58a6ff', max_length=7, verbose_name='Колір')),
                ('is_system', models.BooleanField(default=False, help_text='Системні пакети не можна видалити', verbose_name='Системний')),
                ('modules', models.ManyToManyField(blank=True, help_text='Core-модулі додаються автоматично незалежно від вибору', to='core.moduleregistry', verbose_name='Модулі')),
            ],
            options={
                'verbose_name': 'Пакет модулів',
                'verbose_name_plural': 'Пакети модулів',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bundle',
            field=models.ForeignKey(blank=True, help_text='Якщо вказано — використовується замість дефолтів ролі', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modulebundle', verbose_name='Пакет модулів'),
        ),
    ]
