# Generated by Django 5.2.11 on 2026-04-01 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_allowed_modules_modulebundle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_delete',
            field=models.BooleanField(blank=True, default=None, help_text='Порожньо = за роллю', null=True, verbose_name='Може видаляти'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_export',
            field=models.BooleanField(blank=True, default=None, help_text='Порожньо = за роллю', null=True, verbose_name='Може експортувати'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_import',
            field=models.BooleanField(blank=True, default=None, help_text='Порожньо = за роллю', null=True, verbose_name='Може імпортувати'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_audit',
            field=models.BooleanField(blank=True, default=None, help_text='Порожньо = за роллю', null=True, verbose_name='Бачить журнал аудиту'),
        ),
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('plan', models.CharField(choices=[('trial', '⏳ Пробний'), ('starter', '📦 Стартер'), ('pro', '🚀 Pro'), ('custom', '🎛️ Custom')], default='trial', max_length=20, verbose_name='Тариф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Акаунт',
                'verbose_name_plural': 'Акаунти (тенанти)',
            },
        ),
    ]
