# Generated by Django 5.2.11 on 2026-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenantaccount_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_assistant_role',
            field=models.CharField(choices=[('viewer', 'Viewer — тільки загальні дані'), ('staff', 'Staff — продажі, склад, клієнти'), ('manager', 'Manager — + аналітика, звіти'), ('admin', 'Admin — повний доступ')], default='viewer', help_text='Визначає які дані доступні через AI чат', max_length=20, verbose_name='Роль в AI асистенті'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остання AI активність'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_total_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='AI запитів всього'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_total_spent_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='AI витрачено ($)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Дізнатись через /myid в боті', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='tenantaccount',
            name='company_name',
            field=models.CharField(default='', max_length=200, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='tenantaccount',
            name='owner_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email власника'),
        ),
        migrations.AlterField(
            model_name='tenantaccount',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації'),
        ),
    ]
