# Generated by Django 5.2.11 on 2026-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='denied_models',
            field=models.JSONField(blank=True, default=list, help_text='Список "app_label:ModelName" — моделі заблоковані всередині дозволеного модуля.', verbose_name='Заблоковані моделі'),
        ),
    ]
