# Generated by Django 5.2.11 on 2026-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_module_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imap_enabled',
            field=models.BooleanField(default=False, help_text='Читати листи з особистого ящика і додавати в хронологію клієнтів.', verbose_name='IMAP увімкнено'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_host',
            field=models.CharField(blank=True, help_text='ionos: imap.ionos.de | Gmail: imap.gmail.com', max_length=255, verbose_name='IMAP Host'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP Password'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_port',
            field=models.PositiveSmallIntegerField(default=993, verbose_name='IMAP Port'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_sent_folder',
            field=models.CharField(blank=True, default='INBOX.Sent', help_text='ionos: INBOX.Sent | Gmail: [Gmail]/Sent Mail', max_length=100, verbose_name='Sent папка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='SSL (порт 993)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='imap_user',
            field=models.CharField(blank=True, help_text='Зазвичай повна email-адреса.', max_length=255, verbose_name='IMAP Login'),
        ),
    ]
