# Generated by Django 5.2.11 on 2026-10-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Показувати кнопку помічника в Minerva.', verbose_name='Увімкнено')),
                ('name', models.CharField(default='Minerva', max_length=40, verbose_name='Назва помічника')),
                ('base_url', models.URLField(default='https://app.sevskiy.com', help_text='Без /v1 у кінці, напр. https://app.sevskiy.com або http://192.168.2.68:8787', verbose_name='Адреса RAG API')),
                ('api_key', models.CharField(blank=True, default='', help_text='Bearer-ключ RAG («Копіювати ключ API» у RAG Documents).', max_length=200, verbose_name='Ключ RAG API')),
                ('verify_tls', models.BooleanField(default=True, verbose_name='Перевіряти сертифікат HTTPS')),
                ('timeout', models.PositiveSmallIntegerField(default=20, verbose_name='Тайм-аут запиту, с')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('de', 'Deutsch'), ('en', 'English')], default='uk', max_length=2, verbose_name='Мова відповідей')),
                ('latest_only', models.BooleanField(default=True, verbose_name='Лише останні ревізії даташитів')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання перевірка')),
                ('last_check_result', models.CharField(blank=True, default='', max_length=255, verbose_name='Результат перевірки')),
            ],
            options={
                'verbose_name': 'Налаштування помічника',
                'verbose_name_plural': '⚙️ Налаштування помічника',
            },
        ),
        migrations.CreateModel(
            name='RagConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Розмова',
                'verbose_name_plural': '💬 Розмови',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RagMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('assistant', 'Помічник')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Виконується'), ('done', 'Готово'), ('failed', 'Помилка')], default='done', max_length=10)),
                ('rag_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('stage', models.CharField(blank=True, default='', max_length=200)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('trace', models.JSONField(blank=True, default=list)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag_assistant.ragconversation')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
