# Generated by Django 5.2.11 on 2026-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Ключ')),
                ('scopes', models.JSONField(default=list, verbose_name='Права доступу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Останнє використання')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Дійсний до')),
            ],
            options={
                'verbose_name': 'API Ключ',
                'verbose_name_plural': 'API Ключі',
                'ordering': ['-created_at'],
            },
        ),
    ]
