# Generated by Django 5.2.11 on 2026-10-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='default_source',
            field=models.CharField(blank=True, default='', help_text="Slug джерела (SalesSource) для замовлень, створених цим ключем, якщо в запиті не вказано 'source'. Напр.: webshop", max_length=32, verbose_name='Джерело замовлень'),
        ),
    ]
