# Generated by Django 5.2.11 on 2026-10-01 18:20

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apikey_default_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('url', models.URLField(help_text='HTTPS-адреса, куди Minerva надсилатиме POST з подією', max_length=500, verbose_name='URL отримувача')),
                ('secret', models.CharField(default=api.models._webhook_secret, help_text='Використовується для HMAC-SHA256 підпису (X-Minerva-Signature)', max_length=80, verbose_name='Секрет підпису')),
                ('events', models.JSONField(blank=True, default=list, help_text='Порожньо = всі події', verbose_name='Події')),
                ('order_sources', models.CharField(blank=True, default='', help_text='Через кому, напр.: webshop. Порожньо = замовлення з усіх джерел. Стосується order.* і shipment.*', max_length=255, verbose_name='Тільки джерела замовлень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання доставка')),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Останній HTTP-код')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='Невдач поспіль')),
                ('api_key', models.ForeignKey(blank=True, help_text='Заповнюється, якщо вебхук зареєстровано через API', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.apikey', verbose_name='Створено ключем')),
            ],
            options={
                'verbose_name': 'Вебхук',
                'verbose_name_plural': 'Вебхуки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=50, verbose_name='Подія')),
                ('payload', models.JSONField(verbose_name='Дані')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('success', 'Доставлено'), ('failed', 'Помилка')], default='pending', max_length=10, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Спроб')),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP-код')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='Відповідь / помилка')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Наступна спроба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhook')),
            ],
            options={
                'verbose_name': 'Доставка вебхука',
                'verbose_name_plural': 'Журнал вебхуків',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='api_webhook_status_5921e6_idx')],
            },
        ),
    ]
