# Generated by Django 5.2.11 on 2026-10-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_webhooks'),
        ('shop', '0002_multi_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Асортимент і ціни якого магазину бачить цей ключ (/shop/products/) і куди йдуть його замовлення. Порожньо — магазин з кодом = «Джерело замовлень», інакше магазин за замовчуванням.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='shop.shop', verbose_name='Магазин'),
        ),
    ]
