# Generated by Django 5.2.11 on 2026-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_calcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
