# Generated by Django 5.2.11 on 2026-09-14 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0006_alter_companysettings_phone'),
        ('inventory', '0033_rfqemailtemplate_diagram_in_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Початок')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Кінець')),
                ('status', models.CharField(choices=[('idle', 'Очікує'), ('running', 'Виконується'), ('ok', 'Успішно'), ('partial', 'Частково'), ('error', 'Помилка')], default='running', max_length=20, verbose_name='Статус')),
                ('files_downloaded', models.PositiveIntegerField(default=0, verbose_name='Файлів')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('log_output', models.TextField(blank=True, verbose_name='Лог')),
                ('triggered_by', models.CharField(default='manual', max_length=100, verbose_name='Запущено')),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_num', models.CharField(db_index=True, max_length=100, verbose_name='Batch #')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата рахунку')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('file', models.FileField(blank=True, upload_to='scraper/%Y/%m/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_document', to='accounting.expense', verbose_name='Витрата (бухгалтерія)')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scraper_hub.scraperrun')),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'Рахунки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperSiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(choices=[('jlcpcb', 'JLCPCB'), ('ups', 'UPS Billing')], max_length=50, unique=True, verbose_name='Сайт')),
                ('username', models.CharField(max_length=200, verbose_name='Логін / Email')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('cron_schedule', models.CharField(blank=True, default='0 9 * * 1', help_text='Cron-вираз для автозапуску (напр. "0 9 * * 1" = пн 9:00). Порожньо — лише вручну.', max_length=100, verbose_name='Cron-розклад')),
                ('lookback_days', models.PositiveIntegerField(default=30, help_text='Скільки днів назад перевіряти рахунки при кожному запуску.', verbose_name='Глибина пошуку (днів)')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Email-сповіщення')),
                ('notify_telegram', models.BooleanField(default=False, verbose_name='Telegram-сповіщення')),
                ('auto_create_expense', models.BooleanField(default=True, help_text='Автоматично створювати запис Expense після завантаження PDF.', verbose_name='Авто-витрата в бухгалтерії')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній запуск')),
                ('last_run_status', models.CharField(choices=[('idle', 'Очікує'), ('running', 'Виконується'), ('ok', 'Успішно'), ('partial', 'Частково'), ('error', 'Помилка')], default='idle', max_length=20, verbose_name='Статус')),
                ('last_run_files', models.PositiveIntegerField(default=0, verbose_name='Завантажено файлів')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_configs', to='accounting.expensecategory', verbose_name='Категорія витрат')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_configs', to='inventory.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Scraper — сайт',
                'verbose_name_plural': 'Scraper — сайти',
            },
        ),
        migrations.AddField(
            model_name='scraperrun',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scraper_hub.scrapersiteconfig'),
        ),
    ]
