# Generated by Django 5.2.11 on 2026-09-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlcpcb', '0007_add_jlcorderline'),
        ('scraper_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdocument',
            name='jlc_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_documents', to='jlcpcb.jlcorder', verbose_name='JLCPCB замовлення'),
        ),
    ]
