# Generated by Django 5.2.11 on 2026-05-11 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0014_customertimeline_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Наприклад: Slavik Pryimak або Minerva Support', max_length=200, verbose_name="Ім'я відправника")),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email адреса')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основний акаунт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('imap_host', models.CharField(default='imap.ionos.de', max_length=200, verbose_name='IMAP хост')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='IMAP порт')),
                ('imap_use_ssl', models.BooleanField(default=True, verbose_name='SSL')),
                ('imap_username', models.CharField(max_length=200, verbose_name='IMAP логін')),
                ('imap_password', models.CharField(max_length=500, verbose_name='IMAP пароль')),
                ('imap_folder_inbox', models.CharField(default='INBOX', max_length=200, verbose_name='Папка вхідних')),
                ('imap_folder_sent', models.CharField(default='Gesendete Objekte', help_text='IONOS: Gesendete Objekte | Gmail: [Gmail]/Sent Mail', max_length=200, verbose_name='Папка надісланих')),
                ('smtp_host', models.CharField(default='smtp.ionos.de', max_length=200, verbose_name='SMTP хост')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP порт')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='SSL')),
                ('smtp_username', models.CharField(max_length=200, verbose_name='SMTP логін')),
                ('smtp_password', models.CharField(max_length=500, verbose_name='SMTP пароль')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання синхронізація')),
                ('sync_days_back', models.PositiveIntegerField(default=30, verbose_name='Синхронізувати за N днів')),
                ('last_seen_uid', models.PositiveIntegerField(default=0, verbose_name='Останній UID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Email акаунт',
                'verbose_name_plural': 'Email акаунти',
                'ordering': ['-is_primary', 'email_address'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_uid', models.PositiveIntegerField(default=0)),
                ('message_id', models.CharField(blank=True, max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('folder', models.CharField(choices=[('inbox', 'Вхідні'), ('sent', 'Надіслані'), ('draft', 'Чернетки'), ('trash', 'Кошик'), ('spam', 'Спам')], default='inbox', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_email', models.CharField(max_length=500)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('bcc_emails', models.JSONField(default=list)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('attachments', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_reply_draft', models.TextField(blank=True)),
                ('ai_translated', models.TextField(blank=True)),
                ('ai_translate_to', models.CharField(blank=True, max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_assistant.emailaccount')),
            ],
            options={
                'verbose_name': 'Email лист',
                'verbose_name_plural': 'Email листи',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(default=list)),
                ('bcc_emails', models.JSONField(default=list)),
                ('body', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='email_assistant.emailaccount')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='email_assistant.emailmessage')),
            ],
            options={
                'verbose_name': 'Чернетка',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_auto_suggest_reply', models.BooleanField(default=True, verbose_name='AI автоматично пропонує відповідь')),
                ('ai_auto_translate', models.BooleanField(default=False, verbose_name='AI автоматично перекладає листи')),
                ('ai_translate_to', models.CharField(choices=[('uk', 'Українська'), ('de', 'Deutsch'), ('en', 'English')], default='uk', max_length=10, verbose_name='Мова перекладу')),
                ('deadline_detection', models.BooleanField(default=True, verbose_name='Визначати дедлайни в листах')),
                ('sync_to_crm_timeline', models.BooleanField(default=True, help_text='Листи від/до CRM клієнтів додаються в CustomerTimeline', verbose_name='Синхронізувати з CRM хронологією')),
                ('signature', models.TextField(blank=True, verbose_name='Підпис')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Налаштування Email асистента',
            },
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(max_length=500)),
                ('participants', models.JSONField(default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('has_unread', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='email_assistant.emailaccount')),
                ('crm_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_threads', to='crm.customer', verbose_name='CRM клієнт')),
            ],
            options={
                'verbose_name': 'Гілка листування',
                'verbose_name_plural': 'Гілки листування',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='email_assistant.emailthread'),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('account', 'imap_uid', 'folder')},
        ),
    ]
