# Generated by Django 5.2.11 on 2026-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_assistant', '0003_emailmessage_imap_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='signature',
            field=models.TextField(blank=True, default='', help_text="Підпис для цього акаунту. {name} = ваше ім'я. Якщо порожньо — береться з профілю.", verbose_name='Підпис листа'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='imap_folder_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Оригінальна назва папки на IMAP-сервері (напр. "Meine Order")', max_length=200, verbose_name='Папка IMAP'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='mark_read_on_server',
            field=models.BooleanField(default=True, verbose_name='Помічати прочитані на IMAP-сервері'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='signature',
            field=models.TextField(blank=True, verbose_name='Підпис (застарілий — використовуй підпис акаунту)'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='signature_position',
            field=models.CharField(choices=[('after_reply', 'Після мого тексту'), ('end', 'В кінці')], default='after_reply', max_length=20, verbose_name='Позиція підпису'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='telegram_notify_new',
            field=models.BooleanField(default=True, verbose_name='Telegram: нові листи'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='telegram_quiet_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Тихий режим з'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='telegram_quiet_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Тихий режим до'),
        ),
    ]
