# Generated by Django 5.2.11 on 2026-05-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_assistant', '0004_alter_emailaccount_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=2, help_text='Як часто браузер перевіряє нові листи (мін. 1).', verbose_name='Автооновлення кожні N хвилин'),
        ),
    ]
