# Generated by Django 5.2.11 on 2026-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_assistant', '0005_sync_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='signature_position',
            field=models.CharField(choices=[('after_reply', 'Після мого тексту (перед цитатою)'), ('end', 'В кінці (після цитати)')], default='after_reply', max_length=20, verbose_name='Позиція підпису'),
        ),
    ]
