# Generated by Django 5.2.11 on 2026-05-11 14:40

from django.db import migrations


def backfill_imap_folder_name(apps, schema_editor):
    """Set imap_folder_name for existing inbox/sent messages that have it empty."""
    EmailMessage = apps.get_model('email_assistant', 'EmailMessage')
    EmailAccount = apps.get_model('email_assistant', 'EmailAccount')

    account_cache = {}
    to_update = []

    for msg in EmailMessage.objects.filter(imap_folder_name='').select_related():
        acc_id = msg.account_id
        if acc_id not in account_cache:
            try:
                acc = EmailAccount.objects.get(pk=acc_id)
                account_cache[acc_id] = acc
            except EmailAccount.DoesNotExist:
                continue
        acc = account_cache[acc_id]
        if msg.folder == 'inbox':
            msg.imap_folder_name = acc.imap_folder_inbox or 'INBOX'
        elif msg.folder == 'sent':
            msg.imap_folder_name = acc.imap_folder_sent or 'Gesendete Objekte'
        else:
            msg.imap_folder_name = msg.folder
        to_update.append(msg)

    if to_update:
        EmailMessage.objects.bulk_update(to_update, ['imap_folder_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('email_assistant', '0006_signature_position'),
    ]

    operations = [
        migrations.RunPython(backfill_imap_folder_name, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('account', 'imap_uid', 'imap_folder_name')},
        ),
    ]
