# Generated by Django 5.2.11 on 2026-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_assistant', '0013_emailrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrule',
            name='action',
            field=models.CharField(choices=[('mark_read', 'Позначити прочитаним'), ('mark_spam', 'Позначити спамом'), ('move_folder', 'Перемістити до папки'), ('star', 'Позначити зірочкою'), ('trash', 'Видалити'), ('add_to_calendar', 'Додати в календар (email follow-up)')], default='mark_read', max_length=20, verbose_name='Дія'),
        ),
    ]
