# Generated by Django 5.2.10 on 2026-02-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('sku_short', models.CharField(blank=True, default='', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('antenna', 'Antenna'), ('cable', 'Cable'), ('other', 'Other')], default='other', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=128, unique=True)),
                ('tx_type', models.CharField(choices=[('INITIAL', 'Initial stock'), ('SALE', 'Sale'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ref_doc', models.CharField(blank=True, default='', max_length=255)),
                ('tx_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'location'], name='inventory_i_product_3704ca_idx'), models.Index(fields=['tx_type'], name='inventory_i_tx_type_484cc4_idx'), models.Index(fields=['tx_date'], name='inventory_i_tx_date_39cd1a_idx')],
            },
        ),
    ]
