# Generated by Django 5.2.10 on 2026-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('antenna', 'Antenna'), ('filter', 'Filter'), ('cable', 'Cable'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
