# Generated by Django 5.2.10 on 2026-02-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per', models.PositiveIntegerField(default=1)),
                ('optional', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_product_3704ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_tx_type_484cc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_tx_date_39cd1a_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('none', 'No BOM'), ('key', 'Key components (simple BOM)'), ('full', 'Full BOM')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('finished', 'Finished goods (sellable)'), ('component', 'Component / part (for assembly)')], default='finished', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('Initial stock', 'Initial stock'), ('Receipt', 'Receipt'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('antenna', 'Antenna'), ('cable', 'Cable'), ('filter', 'Filter'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='productalias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productcomponent',
            unique_together={('parent', 'component')},
        ),
    ]
