# Generated by Django 5.2.10 on 2026-02-05 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productcomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
