# Generated by Django 5.2.10 on 2026-02-05 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorytransaction_tx_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('INITIAL', 'Initial stock'), ('SALE', 'Sale'), ('RECEIPT', 'Receipt'), ('ADJUSTMENT', 'Adjustment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('none', 'No BOM (ready to sell)'), ('simple', 'Simple BOM (few key parts)'), ('full', 'Full BOM (many parts)')], default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('antenna', 'Antenna'), ('filter', 'Filter'), ('cable', 'Cable'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('finished', 'Finished product'), ('component', 'Component / part')], default='finished', max_length=16),
        ),
        migrations.AlterField(
            model_name='productalias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'location'], name='inventory_i_product_3704ca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tx_type'], name='inventory_i_tx_type_484cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tx_date'], name='inventory_i_tx_date_39cd1a_idx'),
        ),
    ]
