# Generated by Django 5.2.10 on 2026-02-05 11:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorytransaction_location_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_product_3704ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_tx_date_39cd1a_idx',
        ),
        migrations.RenameField(
            model_name='productcomponent',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='qty_per',
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='qty_per_parent',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='external_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('NONE', 'No BOM'), ('KEY', 'Key components (simple BOM)'), ('FULL', 'Full BOM')], default='NONE', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('SELLABLE', 'Sellable (ready to ship)'), ('COMPONENT', 'Component (used for assemblies)'), ('ASSEMBLY', 'Assembly (built from components)')], default='SELLABLE', max_length=16),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'tx_date'], name='inventory_i_product_997fdd_idx'),
        ),
    ]
