# Generated by Django 5.2.10 on 2026-02-05 12:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventorytransaction_inventory_i_product_3704ca_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('supplier_order_no', models.CharField(blank=True, default='', max_length=128)),
                ('shipping_service', models.CharField(blank=True, default='', max_length=128)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ordered', 'Ordered'), ('Partial', 'Partially received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_text', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty_ordered', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('qty_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('affects_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_tx_type_484cc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_product_997fdd_idx',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='external_key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('Initial stock', 'Initial stock'), ('Receipt', 'Receipt'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('None', 'No BOM'), ('Key', 'Key components (simple BOM)'), ('Full', 'Full BOM (many parts)')], default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Antenna', 'Antenna'), ('Cable', 'Cable'), ('Filter', 'Filter'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('Finished', 'Finished (sellable item)'), ('Component', 'Component (used for assemblies)'), ('Assembly', 'Assembly (built from components)')], default='Finished', max_length=32),
        ),
        migrations.AlterField(
            model_name='productalias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
    ]
