# Generated by Django 5.2.10 on 2026-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorder_purchaseorderline_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('none', 'No BOM'), ('KEY', 'Key components (simple BOM)'), ('FULL', 'Full BOM (many parts)')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('antenna', 'Antenna'), ('cable', 'Cable'), ('filter', 'Filter'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('finished', 'Finished (sellable item)'), ('component', 'Component (used for assemblies)'), ('ASSEMBLY', 'Assembly (built from components)')], default='finished', max_length=32),
        ),
    ]
