# Generated by Django 5.2.10 on 2026-02-05 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_bom_type_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomponent',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='po',
            new_name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='qty_per_parent',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier_order_no',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='affects_stock',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='sku_text',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='qty_per',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='currency',
            field=models.CharField(blank=True, default='EUR', max_length=8),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='external_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('none', 'No BOM'), ('key', 'Key components (simple BOM)')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('antenna', 'Antenna'), ('cable', 'Cable'), ('filter', 'Filter'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('finished', 'Finished (sellable)'), ('component', 'Component (used for assembly)')], default='finished', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_short',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productalias',
            name='alias',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(blank=True, default='EUR', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_service',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partial', 'Partial'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'location'], name='inventory_i_product_3704ca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tx_type'], name='inventory_i_tx_type_484cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tx_date'], name='inventory_i_tx_date_39cd1a_idx'),
        ),
    ]
