# Generated by Django 5.2.10 on 2026-02-05 15:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_notes_productcomponent_note_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_product_3704ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_tx_type_484cc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorytransaction',
            name='inventory_i_tx_date_39cd1a_idx',
        ),
        migrations.RenameField(
            model_name='productcomponent',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='purchase_order',
            new_name='po',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='productcomponent',
            name='qty_per',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='code',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='notes',
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='qty_per_parent',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_order_no',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='affects_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='sku_text',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='external_key',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('Initial stock', 'Initial stock'), ('Receipt', 'Receipt'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('none', 'No BOM'), ('KEY', 'Key components (simple BOM)'), ('FULL', 'Full BOM (many parts)')], default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('antenna', 'Antenna'), ('cable', 'Cable'), ('filter', 'Filter'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('finished', 'Finished (sellable item)'), ('component', 'Component (used for assemblies)'), ('ASSEMBLY', 'Assembly (built from components)')], default='finished', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_short',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='productalias',
            name='alias',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='EUR', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_service',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ordered', 'Ordered'), ('Partial', 'Partially received'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
