# Generated by Django 5.2.11 on 2026-02-09 14:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('piece', 'Штуки (цілі числа)'), ('meter', 'Метри (дробні числа)'), ('kilogram', 'Кілограми (дробні числа)'), ('liter', 'Літри (дробні числа)'), ('set', 'Комплекти (цілі числа)')], default='piece', help_text='Визначає чи товар вимірюється в цілих числах (штуки) чи дробних (метри, кг)', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='qty_per',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Кількість компонента на одиницю готового виробу', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
