# Generated by Django 5.2.11 on 2026-02-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_unit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Аналіз запасів',
                'verbose_name_plural': '📊 Аналіз запасів',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
    ]
