# Generated by Django 5.2.11 on 2026-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_supplier_addr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(help_text='Латиниця, без пробілів. Зберігається в товарах.', max_length=64, unique=True, verbose_name='Код (slug)'),
        ),
    ]
