# Generated by Django 5.2.11 on 2026-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productcategory_country_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_weight_g',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Вага нетто (г/шт)'),
        ),
    ]
