# Generated by Django 5.2.11 on 2026-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_weight_decimal_delivered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduct_on', models.CharField(choices=[('creation', 'При створенні замовлення'), ('shipped', 'При зміні статусу на «Відправлено»'), ('delivered', 'При зміні статусу на «Доставлено»')], default='creation', help_text='Коли автоматично зменшувати залишок при продажах.', max_length=16, verbose_name='Списувати товар зі складу')),
                ('add_on_po_receive', models.BooleanField(default=True, help_text='Автоматично збільшувати залишок при зміні qty_received у замовленні на закупівлю.', verbose_name='Додавати при надходженні закупівлі')),
                ('default_location', models.CharField(default='MAIN', help_text='Код складської локації для нових транзакцій (наприклад: MAIN, WAREHOUSE-A).', max_length=50, verbose_name='Локація за замовчуванням')),
                ('allow_negative_stock', models.BooleanField(default=True, help_text='Дозволити відвантаження навіть якщо залишок менший за 0.', verbose_name="Дозволити від'ємний залишок")),
                ('low_stock_alert_enabled', models.BooleanField(default=True, help_text='Показувати попередження в інтерфейсі для товарів нижче точки дозамовлення.', verbose_name='Попередження про низький залишок')),
            ],
            options={
                'verbose_name': 'Налаштування складу',
                'verbose_name_plural': '⚙️ Налаштування складу',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet_url',
            field=models.URLField(blank=True, default='', verbose_name='Посилання на Datasheet'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Зображення (файл)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Зображення (URL)'),
        ),
    ]
