# Generated by Django 5.2.11 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventorysettings_product_datasheet_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet_file',
            field=models.FileField(blank=True, help_text='Завантажте PDF з ПК. Якщо заповнено — має пріоритет над посиланням.', null=True, upload_to='products/datasheets/', verbose_name='Datasheet (PDF файл)'),
        ),
    ]
