# Generated by Django 5.2.11 on 2026-04-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_product_datasheet_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='use_reservation',
            field=models.BooleanField(default=False, help_text='При надходженні замовлення — створювати резерв (🔒 Резерв) замість негайного списання. Товар залишається на складі, але позначається як зарезервований. При переведенні замовлення у «Відправлено» — резерв автоматично конвертується у фактичне списання.', verbose_name='Бронювати замовлення (не списувати одразу)'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Adjustment', 'Adjustment'), ('Reserved', 'Резерв')], max_length=20),
        ),
    ]
