# Generated by Django 5.2.11 on 2026-05-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_performed_by_reserved_use_reservation'),
        ('shipping', '0041_incoming_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Перевізник')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Номер відстеження')),
                ('tracking_url', models.URLField(blank=True, default='', verbose_name='Посилання трекінгу')),
                ('status', models.CharField(choices=[('pending', 'Очікує відправлення'), ('in_transit', 'В дорозі'), ('customs', 'На митниці'), ('arrived', 'Прибув на склад'), ('delivered', 'Отримано'), ('exception', 'Проблема')], default='pending', max_length=20, verbose_name='Статус')),
                ('carrier_status_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Статус від перевізника')),
                ('origin_country', models.CharField(blank=True, default='', max_length=3, verbose_name='Країна відправлення')),
                ('origin_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Місто відправлення')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Очікувана дата')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='Відправлено')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Отримано')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Нотатки')),
                ('tracking_events', models.JSONField(blank=True, default=list, verbose_name='Події трекінгу')),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній трекінг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.carrier', verbose_name='Перевізник (API)')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_shipments', to='inventory.purchaseorder', verbose_name='Замовлення (PO)')),
            ],
            options={
                'verbose_name': 'Вхідне відправлення',
                'verbose_name_plural': 'Вхідні відправлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
