# Generated by Django 5.2.11 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_rfqemailtemplate_diagram_in_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локація складу', 'verbose_name_plural': '📍 Локації складу'},
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('finished', 'Готова продукція 🏭'), ('components', 'Компоненти & Матеріали 🔧'), ('other', 'Інше (загальний склад)')], default='other', help_text='Розділяє готову продукцію від компонентів для збирання', max_length=20, verbose_name='Тип складу'),
        ),
    ]
