# Generated by Django 5.2.11 on 2026-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_location_options_location_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Порожньо — використовується «Ціна продажу».', max_digits=18, null=True, verbose_name='Ціна в магазині (нетто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_visible',
            field=models.BooleanField(db_index=True, default=False, help_text="Товар з'являється в магазині на сайті (через API).", verbose_name='Показувати в інтернет-магазині'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bom_type',
            field=models.CharField(choices=[('none', 'No BOM'), ('key', 'Key components (simple BOM)')], default='none', help_text='Key = має список компонентів (БОМ); None = простий товар без розбірки', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('finished', 'Finished (sellable)'), ('component', 'Component (used for assembly)')], default='finished', help_text='Finished = готовий виріб для продажу; Component = запчастина для складання в БОМ', max_length=20),
        ),
    ]
