# Generated by Django 5.2.11 on 2026-10-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_shop_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Активний'), ('nrnd', 'Не рекомендовано для нових розробок (NRND)'), ('discontinued', 'Знято з виробництва (EOL)')], default='active', help_text='NRND — радимо нову версію; EOL — знято з виробництва, в магазині продається лише залишок.', max_length=16, verbose_name='Життєвий цикл'),
        ),
        migrations.AddField(
            model_name='product',
            name='successor',
            field=models.ForeignKey(blank=True, help_text='Показується на сайті біля NRND / EOL товару як «Nachfolger».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecessors', to='inventory.product', verbose_name='Рекомендована заміна (нова версія)'),
        ),
    ]
