# Generated by Django 5.2.11 on 2026-10-06 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_product_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price_currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Валюта базових цін'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_prices',
            field=models.JSONField(blank=True, default=list, help_text='[{"min_qty": 1, "unit_price": "4.89"}, {"min_qty": 10, "unit_price": "4.52"}, …]', verbose_name='Базові ціни (ступені)'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_prices_source',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Звідки базові ціни'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_prices_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Базові ціни змінено'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_prices_updated_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Ким змінено базові ціни'),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли')),
                ('user_label', models.CharField(blank=True, default='', max_length=150, verbose_name='Хто')),
                ('source', models.CharField(choices=[('digikey', 'Імпорт з DigiKey'), ('manual', 'Вручну'), ('api', 'API'), ('migration', 'Перенесення даних')], default='manual', max_length=12, verbose_name='Джерело')),
                ('currency', models.CharField(blank=True, default='', max_length=3, verbose_name='Валюта')),
                ('old_prices', models.JSONField(blank=True, default=list, verbose_name='Було')),
                ('new_prices', models.JSONField(blank=True, default=list, verbose_name='Стало')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примітка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Зміна базових цін',
                'verbose_name_plural': 'Історія базових цін',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
