# Generated by Django 5.2.11 on 2026-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_base_prices_from_digikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Будь-яка зміна картки товару (для API changed_since / RAG).', verbose_name='Змінено'),
        ),
    ]
