# Generated by Django 5.2.11 on 2026-05-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наприклад: Packing List EN, CN23 Митна декларація', max_length=200, verbose_name='Назва шаблону')),
                ('doc_type', models.CharField(choices=[('packing_list', 'Packing List (Пакувальний лист)'), ('proforma', 'Proforma Invoice (Проформа)'), ('invoice', 'Invoice / Рахунок-фактура'), ('cn23', 'CN23 Митна декларація'), ('custom', 'Кастомний документ')], default='custom', max_length=30, verbose_name='Тип документа')),
                ('module', models.CharField(choices=[('sales', 'Продажі (замовлення)'), ('crm', 'Клієнти'), ('any', 'Всі модулі')], default='sales', help_text="Кнопка генерації з'явиться в картці цього модуля", max_length=20, verbose_name="Прив'язати до модуля")),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('uk', 'Українська')], default='en', max_length=5, verbose_name='Мова документа')),
                ('template_file', models.FileField(help_text='Завантаж .docx файл з {{змінними}} в тексті. Дивись "Довідник змінних" нижче для повного списку.', upload_to='document_templates/', verbose_name='Word шаблон (.docx)')),
                ('description', models.TextField(blank=True, help_text='Для чого використовується цей шаблон', verbose_name='Опис шаблону')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_default', models.BooleanField(default=False, help_text='Цей шаблон буде першим в списку для свого типу', verbose_name='За замовчуванням')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_templates', to=settings.AUTH_USER_MODEL, verbose_name='Завантажив')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблони документів',
                'ordering': ['sort_order', 'doc_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(blank=True, max_length=20, verbose_name='Модуль')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID об'єкта")),
                ('source_repr', models.CharField(blank=True, max_length=300, verbose_name='Опис')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated_documents/%Y/%m/', verbose_name='Word файл (.docx)')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_documents/%Y/%m/', verbose_name='PDF файл')),
                ('status', models.CharField(choices=[('generating', '⏳ Генерується'), ('ready', '✅ Готовий'), ('error', '❌ Помилка')], default='generating', max_length=20)),
                ('error_msg', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_docs', to=settings.AUTH_USER_MODEL, verbose_name='Генерував')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_docs', to='documents.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Згенерований документ',
                'verbose_name_plural': 'Згенеровані документи',
                'ordering': ['-created_at'],
            },
        ),
    ]
