# Generated by Django 5.2.11 on 2026-05-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('sales', '0035_salesorder_status_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='source',
            field=models.ForeignKey(blank=True, help_text="Залиш порожнім — шаблон буде доступний для всіх джерел. Якщо вказано — кнопка з'явиться тільки для замовлень цього джерела.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates', to='sales.salessource', verbose_name='Джерело замовлення'),
        ),
    ]
