# Generated by Django 5.2.11 on 2026-06-03 15:33

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttemplate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(help_text='Завантаж .docx файл з {{змінними}} в тексті. Дивись "Довідник змінних" нижче для повного списку.', upload_to='document_templates/', validators=[documents.models._validate_docx], verbose_name='Word шаблон (.docx)'),
        ),
    ]
