# Generated by Django 5.2.11 on 2026-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_systemsettings_default_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_language', models.CharField(choices=[('en', 'English (EN)'), ('de', 'Deutsch / English (DE+EN двомовні)'), ('deu', 'Deutsch (тільки DE)')], default='en', help_text='Мова заголовків і тексту у PDF (EN — англійська, DE — двомовні DE/EN).', max_length=5, verbose_name='Мова документів')),
                ('packing_list_show_prices', models.BooleanField(default=False, help_text='Додається колонка Unit Price та Total у таблицю позицій.', verbose_name='Показувати ціни у пакувальному листі')),
                ('packing_list_footer_note', models.TextField(blank=True, default='', help_text='Додатковий текст у нижньому колонтитулі. Наприклад: "For customs use only."', verbose_name='Нотатка внизу пакувального листа')),
                ('proforma_payment_terms', models.CharField(default='Payment within 30 days', help_text='Відображається в нижній частині proforma invoice.', max_length=255, verbose_name='Умови оплати (Proforma)')),
                ('proforma_notes', models.TextField(blank=True, default='', help_text='Додатковий текст у нижній частині proforma invoice.', verbose_name='Примітки до proforma')),
                ('customs_default_type', models.CharField(choices=[('SALE', 'Sale / Verkauf — продаж'), ('SAMPLE', 'Gift / Geschenk — подарунок'), ('TRANSFER', 'Sample / Muster — зразок'), ('WARRANTY', 'Return / Rücksendung — повернення'), ('OTHER', 'Other / Sonstiges — інше')], default='SALE', help_text='Використовується коли у замовленні не вказано тип документа.', max_length=10, verbose_name='Тип декларації CN23 за замовчуванням')),
                ('customs_reason', models.CharField(blank=True, default='Gewerblich / Commercial', help_text='Підставляється у CN23 якщо у товарі немає назви для документів.', max_length=255, verbose_name='Опис відправлення (fallback)')),
            ],
            options={
                'verbose_name': 'Налаштування документів',
                'verbose_name_plural': 'Налаштування документів',
            },
        ),
    ]
