# Generated by Django 5.2.11 on 2026-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_documentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, help_text='Увімкніть після налаштування SMTP нижче.', verbose_name='Надсилати email-сповіщення')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('email_port', models.PositiveSmallIntegerField(default=587, verbose_name='SMTP Port')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Зазвичай порт 587. Вимкни якщо використовуєш SSL (порт 465).', verbose_name='TLS (STARTTLS)')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Зазвичай порт 465. Несумісне з TLS — увімкни лише одне.', verbose_name='SSL')),
                ('email_host_user', models.CharField(blank=True, max_length=255, verbose_name='SMTP Login (email)')),
                ('email_host_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP Password')),
                ('email_from', models.CharField(blank=True, help_text='Якщо порожньо — використовується SMTP Login.', max_length=255, verbose_name='Від кого (From)')),
                ('email_to', models.TextField(blank=True, help_text='Email-адреси через кому: admin@example.com, boss@company.com', verbose_name='Отримувачі (To)')),
                ('stock_alerts_enabled', models.BooleanField(default=True, help_text='Товари з запасом менше 1.5 місяців (на основі продажів за 90 днів).', verbose_name='Critical stock alerts')),
                ('deadline_alerts_enabled', models.BooleanField(default=True, help_text='Замовлення з простроченим дедлайном доставки.', verbose_name='Overdue deadline alerts')),
                ('deadline_overdue_days', models.PositiveSmallIntegerField(default=0, help_text='0 = в день дедлайну і кожного наступного. 1 = наступного дня і далі.', verbose_name='Оповіщати через N днів після дедлайну')),
                ('alert_min_interval_hours', models.PositiveSmallIntegerField(default=12, help_text='Захист від дублювання при автоматичному запуску через cron.', verbose_name='Мінімальний інтервал між надсиланнями (год)')),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True, verbose_name='Останнє надсилання')),
            ],
            options={
                'verbose_name': 'Налаштування сповіщень',
                'verbose_name_plural': 'Налаштування сповіщень',
            },
        ),
    ]
