# Generated by Django 5.2.11 on 2026-03-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_notificationsettings_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_on_cancelled',
            field=models.BooleanField(default=False, help_text='Сповістити при скасуванні замовлення.', verbose_name='→ Скасовано'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_on_delivered',
            field=models.BooleanField(default=True, help_text='Сповістити коли замовлення доставлено.', verbose_name='→ Доставлено'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_on_processing',
            field=models.BooleanField(default=False, help_text='Сповістити коли статус змінився на «В обробці».', verbose_name='→ В обробці'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_on_shipped',
            field=models.BooleanField(default=True, help_text='Сповістити коли замовлення відправлено.', verbose_name='→ Відправлено'),
        ),
    ]
