# Generated by Django 5.2.11 on 2026-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_sync_result_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='sync_skip_if_no_changes',
            field=models.BooleanField(default=True, help_text='Увімкнено — сповіщення надходить лише коли є реальні зміни.', verbose_name='Не надсилати якщо змін не виявлено'),
        ),
    ]
