# Generated by Django 5.2.11 on 2026-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_themesettings_sb_head_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Показується на лендінгу, отримує форми контакту', max_length=254, verbose_name='Контактний email'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон підтримки'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_tagline',
            field=models.CharField(blank=True, default='Business Intelligence для малого бізнесу', help_text='Показується на лендінгу', max_length=300, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_telegram',
            field=models.CharField(blank=True, help_text='Наприклад: @minerva_support', max_length=100, verbose_name='Telegram підтримки'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ліцензія діє до'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_key',
            field=models.CharField(blank=True, help_text='Отримайте на minerva-bi.com після придбання', max_length=500, verbose_name='Ліцензійний ключ'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='license_package',
            field=models.CharField(choices=[('trial', 'Пробна версія (30 днів)'), ('starter', 'Starter'), ('business', 'Business'), ('custom', 'Custom / Self-hosted')], default='trial', max_length=20, verbose_name='Пакет ліцензії'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_domain',
            field=models.CharField(default='localhost:8000', help_text='Використовується в посиланнях email листів (password reset). Приклади: akustik.synology.me:81 | minerva-bi.com | localhost:8000', max_length=200, verbose_name='Домен системи'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', help_text='HTTPS для production, HTTP для локальної мережі', max_length=5, verbose_name='Протокол'),
        ),
    ]
