# Generated by Django 5.2.11 on 2026-04-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_systemsettings_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_email',
            field=models.BooleanField(default=True, verbose_name='Email звіт'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_enabled',
            field=models.BooleanField(default=False, help_text='Надсилати зведений звіт за розкладом.', verbose_name='Увімкнути звіт'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Щодня'), ('weekly', 'Щотижня')], default='daily', max_length=10, verbose_name='Частота'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_include_delivered',
            field=models.BooleanField(default=True, help_text='Замовлення зі статусом «Доставлено» за звітний період.', verbose_name='✅ Доставлені'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_include_new_orders',
            field=models.BooleanField(default=True, help_text='Замовлення що надійшли з моменту попереднього звіту.', verbose_name='🆕 Нові замовлення'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_include_overdue',
            field=models.BooleanField(default=True, help_text='Замовлення де дедлайн уже минув.', verbose_name='⏰ Прострочені дедлайни'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_include_pending',
            field=models.BooleanField(default=True, help_text='Замовлення з дедлайном, ще не відправлені.', verbose_name='📦 Очікують відправки'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_include_stock',
            field=models.BooleanField(default=True, help_text='Товари з запасом менше 1.5 місяців.', verbose_name='🔥 Критичний залишок'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останній звіт надіслано'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_send_time',
            field=models.TimeField(default='08:00', help_text='Час по серверному часовому поясу (Europe/Berlin).', verbose_name='Час надсилання'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_telegram',
            field=models.BooleanField(default=True, verbose_name='Telegram звіт'),
        ),
    ]
