# Generated by Django 5.2.11 on 2026-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_digest_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_holiday_country',
            field=models.CharField(choices=[('UA', 'Україна'), ('DE', 'Німеччина'), ('PL', 'Польща'), ('US', 'США')], default='UA', max_length=2, verbose_name='Країна свят'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_skip_holidays',
            field=models.BooleanField(default=False, help_text='Перевіряє через Nager.Date API. Якщо API недоступний — надсилає.', verbose_name='Не надсилати у свята'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_skip_weekends',
            field=models.BooleanField(default=False, help_text='Субота та неділя — звіт пропускається.', verbose_name='Не надсилати у вихідні'),
        ),
    ]
