# Generated by Django 5.2.11 on 2026-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_digest_weekends_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_enabled',
            field=models.BooleanField(default=False, help_text='Увімкніть після налаштування — Мінерва читатиме листи і додаватиме в хронологію клієнтів.', verbose_name='IMAP увімкнено'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_host',
            field=models.CharField(blank=True, default='imap.ionos.de', help_text='ionos: imap.ionos.de | Gmail: imap.gmail.com', max_length=255, verbose_name='IMAP Host'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_inbox_folder',
            field=models.CharField(blank=True, default='INBOX', max_length=100, verbose_name='Inbox папка'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_lookback_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Листи старіші цього терміну ігноруються.', verbose_name='Завантажити за останні N днів'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP Password'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_port',
            field=models.PositiveSmallIntegerField(default=993, help_text='SSL: 993 | STARTTLS: 143', verbose_name='IMAP Port'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_sent_folder',
            field=models.CharField(blank=True, default='INBOX.Sent', help_text='ionos: INBOX.Sent | Gmail: [Gmail]/Sent Mail | Outlook: Sent', max_length=100, verbose_name='Sent папка'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, help_text='Вимкни якщо використовуєш STARTTLS (порт 143).', verbose_name='SSL (порт 993)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='imap_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP Login (email)'),
        ),
    ]
