# Generated by Django 5.2.11 on 2026-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_weekly_monthly_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsettings',
            name='show_auto_pdf_panel',
            field=models.BooleanField(default=True, help_text='Секція з кнопками PDF (Packing List / Proforma / CN23). Вимкни якщо використовуєш тільки Word шаблони (модуль Документи).', verbose_name='Показувати «Автоматичні документи» в картці замовлення'),
        ),
        migrations.AlterField(
            model_name='briefingsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
