# Generated by Django 5.2.11 on 2026-05-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_documentsettings_show_auto_pdf_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_email',
            field=models.BooleanField(default=False, help_text='Надсилати email при зміні статусу відправлення (посилки).', verbose_name='Email: статус посилки'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_on_cancelled',
            field=models.BooleanField(default=False, help_text='Сповістити при скасуванні відправлення.', verbose_name='→ Скасовано (посилка)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_on_delivered',
            field=models.BooleanField(default=True, help_text='Сповістити коли посилка доставлена одержувачу.', verbose_name='→ Доставлено'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_on_error',
            field=models.BooleanField(default=True, help_text='Сповістити при помилці відправлення.', verbose_name='→ Помилка'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_on_in_transit',
            field=models.BooleanField(default=True, help_text='Сповістити коли посилка в дорозі (отримано перевізником).', verbose_name='→ В дорозі'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_on_label_ready',
            field=models.BooleanField(default=False, help_text='Сповістити коли етикетка сформована.', verbose_name='→ Етикетка готова'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_on_submitted',
            field=models.BooleanField(default=False, help_text='Сповістити коли відправлення передано перевізнику.', verbose_name='→ Передано перевізнику'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shipment_telegram',
            field=models.BooleanField(default=True, help_text='Надсилати Telegram при зміні статусу відправлення (посилки).', verbose_name='Telegram: статус посилки'),
        ),
    ]
