# Generated by Django 5.2.11 on 2026-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_update_order_confirm_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='customer_notify_body',
            field=models.TextField(blank=True, default='Dear {customer_name},\n\nYour order #{order_number} has been shipped on {shipped_date}.\n\nCarrier: {carrier}\nTracking number: {tracking_number}\n\nItems shipped:\n{items}\n\nDelivery address:\n{ship_address}\n\nBest regards', help_text='Змінні: {order_number} {customer_name} {tracking_number} {carrier} {shipped_date} {items} {ship_address}', verbose_name='Текст листа клієнту — ЄС (шаблон)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='customer_notify_body_noneu',
            field=models.TextField(blank=True, default="Dear {customer_name},\n\nYour order #{order_number} has been shipped on {shipped_date}.\n\nCarrier: {carrier}\nTracking number: {tracking_number}\n\nItems shipped:\n{items}\n\nDelivery address:\n{ship_address}\n\nPlease note: Your shipment originates from the EU. Depending on your country's import regulations, customs duties and/or import taxes may be charged upon delivery. These fees are the responsibility of the recipient and are not included in the order price. We recommend checking with your local customs authority for more information.\n\nBest regards", help_text='Використовується для країн за межами ЄС (автовизначення за addr_country). Змінні: {order_number} {customer_name} {tracking_number} {carrier} {shipped_date} {items} {ship_address}', verbose_name='Текст листа клієнту — не-ЄС (шаблон)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='customer_notify_subject',
            field=models.CharField(blank=True, default='Ihre Bestellung #{order_number} wurde versendet', help_text='Змінні: {order_number} {customer_name} {tracking_number} {carrier} {shipped_date}', max_length=500, verbose_name='Тема листа клієнту (шаблон)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='order_confirm_notify_auto',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено — лист надсилається автоматично при імпорті або створенні нового замовлення (залежно від фільтра джерел).', verbose_name='Авто-відправка при створенні замовлення'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='order_confirm_notify_cc',
            field=models.CharField(blank=True, help_text='Email-адреси через кому.', max_length=500, verbose_name='CC (копія) за замовчуванням'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='order_confirm_notify_sources',
            field=models.CharField(blank=True, help_text='Slug-коди джерел через кому, для яких діє авто- та ручна відправка. Порожньо = всі джерела. Приклад: digikey, webshop', max_length=500, verbose_name='Джерела (фільтр)'),
        ),
    ]
