# Generated by Django 5.2.11 on 2026-06-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_notify_include_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='dk_unconfirmed_alert_email',
            field=models.BooleanField(default=True, verbose_name='Email нагадування'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='dk_unconfirmed_alert_enabled',
            field=models.BooleanField(default=True, help_text='Якщо замовлення відправлено (є трек-номер), але не підтверджено через DigiKey Marketplace Ship API — надіслати нагадування.', verbose_name='Сповіщення: непідтверджена відправка на DigiKey'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='dk_unconfirmed_alert_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Нагадування надсилається якщо з моменту відправлення пройшло більше N годин без підтвердження на DigiKey.', verbose_name='Через скільки годин нагадувати'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='dk_unconfirmed_alert_telegram',
            field=models.BooleanField(default=True, verbose_name='Telegram нагадування'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='dk_unconfirmed_last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останнє нагадування'),
        ),
    ]
