# Generated by Django 5.2.11 on 2026-04-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_userprofile_ai_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBudgetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('alert_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AI Бюджет (місяць)',
                'verbose_name_plural': 'AI Бюджет по місяцях',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram_private', 'Telegram Приват'), ('telegram_group', 'Telegram Група'), ('webchat', 'WebChat Minerva')], max_length=30, verbose_name='Канал')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Розпочато')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Остання активність')),
                ('is_active', models.BooleanField(default=True)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='core.userprofile', verbose_name='Профіль юзера')),
            ],
            options={
                'verbose_name': 'AI Розмова',
                'verbose_name_plural': 'AI Розмови',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool Result')], max_length=20)),
                ('content', models.TextField(verbose_name='Зміст')),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_result', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aiconversation', verbose_name='Розмова')),
            ],
            options={
                'verbose_name': 'AI Повідомлення',
                'ordering': ['created_at'],
            },
        ),
    ]
