# Generated by Django 5.2.11 on 2026-10-03 06:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0035_shop_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_breaks', models.JSONField(blank=True, default=list, help_text='Знижка від базової ціни (1 шт.) за кількістю, напр. [{"min_qty": 10, "discount": 5}, {"min_qty": 100, "discount": 12}]', verbose_name='Шаблон ступенів цін')),
                ('default_markup', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Для дії «Ціна = закупівля + націнка». 100 % = закупівельна ціна × 2.', max_digits=7, verbose_name='Націнка за замовчуванням, %')),
                ('rounding', models.CharField(choices=[('none', 'Без округлення'), ('0.01', 'До 0,01'), ('0.05', 'До 0,05'), ('0.10', 'До 0,10'), ('0.50', 'До 0,50'), ('1.00', 'До 1,00'), ('x.90', 'Закінчення ,90'), ('x.99', 'Закінчення ,99')], default='0.01', max_length=8, verbose_name='Округлення цін')),
            ],
            options={
                'verbose_name': 'Налаштування цін магазину',
                'verbose_name_plural': '⚙️ Налаштування цін',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Товар магазину',
                'verbose_name_plural': '🏪 Товари магазину',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='ShopPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Від кількості, шт.')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ціна за шт. (нетто)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_tiers', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ступінь ціни',
                'verbose_name_plural': 'Ступені цін',
                'ordering': ['product', 'min_qty'],
                'constraints': [models.UniqueConstraint(fields=('product', 'min_qty'), name='uniq_shop_tier_qty')],
            },
        ),
    ]
