# Generated by Django 5.2.11 on 2026-10-05 09:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_multi_shop_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='free_shipping_enabled',
            field=models.BooleanField(default=False, help_text='Доставка безкоштовна, коли сума товарів (нетто) досягає порогу. Діє в регіонах, де це дозволено.', verbose_name='Безкоштовна доставка'),
        ),
        migrations.AddField(
            model_name='shop',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Безкоштовно від (нетто)'),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='price_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='100 = як на DigiKey, 95 = на 5 % дешевше.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='% від ціни DigiKey'),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='price_source',
            field=models.CharField(choices=[('manual', 'Вручну'), ('digikey', 'DigiKey (автоматично)')], default='manual', help_text='DigiKey — ціна і ступені беруться з цін офера на DigiKey і оновлюються разом з ними.', max_length=10, verbose_name='Джерело ціни'),
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Регіон')),
                ('countries', models.JSONField(default=list, help_text='Коди ISO через кому: DE, AT, CH. «EU» — усі країни ЄС, «*» — решта світу.', verbose_name='Країни')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Доставка (нетто)')),
                ('free_shipping', models.BooleanField(default=True, help_text='Якщо в магазині увімкнено безкоштовну доставку від порогу.', verbose_name='Діє безкоштовна доставка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('dk_code', models.CharField(blank=True, default='', help_text='Заповнюється при імпорті регіонів з DigiKey.', max_length=40, verbose_name='Код DigiKey')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='shop.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Регіон доставки',
                'verbose_name_plural': '🚚 Регіони доставки',
                'ordering': ['shop', 'sort_order', 'name'],
            },
        ),
    ]
