# Generated by Django 5.2.11 on 2026-10-05 10:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shipping_digikey_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplisting',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sonderangebot: знижка на ціну і всі ступені. 0 — без акції.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Акція: знижка, %'),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='discount_until',
            field=models.DateField(blank=True, help_text='Після цієї дати акція сама припиняється. Порожньо — без кінцевої дати.', null=True, verbose_name='Акція до (включно)'),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='new_until',
            field=models.DateField(blank=True, help_text='До цієї дати на сайті бейдж «Neu», товар показується вгорі каталогу.', null=True, verbose_name='Новинка до (включно)'),
        ),
    ]
