# Generated by Django 5.2.11 on 2026-10-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_product_lifecycle'),
        ('shop', '0006_promo_offers_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplisting',
            name='lifecycle_status',
            field=models.CharField(blank=True, choices=[('', 'Як на складі'), ('active', 'Активний'), ('nrnd', 'Не рекомендовано для нових розробок (NRND)'), ('discontinued', 'Знято з виробництва (EOL)')], default='', help_text='«Як на складі» — статус товару (діє в усіх магазинах). Інше значення — лише для цього магазину.', max_length=16, verbose_name='Життєвий цикл у цьому магазині'),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='successor',
            field=models.ForeignKey(blank=True, help_text='Порожньо — рекомендована заміна з картки товару.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Заміна в цьому магазині'),
        ),
    ]
