# Generated by Django 5.2.11 on 2026-10-06 11:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def digikey_to_base(apps, schema_editor):
    """Джерело ціни «DigiKey» стало «Базові ціни товару» (базові ціни імпортовано з DigiKey в inventory 0038)."""
    apps.get_model("shop", "ShopListing").objects.filter(price_source="digikey").update(price_source="base")


def base_to_digikey(apps, schema_editor):
    apps.get_model("shop", "ShopListing").objects.filter(price_source="base").update(price_source="digikey")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_listing_lifecycle'),
        ('inventory', '0038_base_prices_from_digikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='fx_rates',
            field=models.JSONField(blank=True, default=dict, help_text='Для базових цін в іншій валюті: скільки одиниць валюти магазину за 1 одиницю, напр. {"USD": 0.86} — 1 USD = 0,86 EUR.', verbose_name='Курси валют'),
        ),
        migrations.AlterField(
            model_name='shoplisting',
            name='price_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='100 = як базова ціна, 95 = на 5 % дешевше.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='% від базової ціни'),
        ),
        migrations.AlterField(
            model_name='shoplisting',
            name='price_source',
            field=models.CharField(choices=[('manual', 'Вручну'), ('base', 'Базові ціни товару (автоматично)')], default='manual', help_text='Базові ціни — ціна і ступені беруться з базових цін товару (склад) і оновлюються разом з ними.', max_length=10, verbose_name='Джерело ціни'),
        ),
        migrations.RunPython(digikey_to_base, base_to_digikey),
    ]
