# Generated by Django 5.2.11 on 2026-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[('b2b', 'B2B (компанія)'), ('b2c', 'B2C (фізична особа)'), ('distributor', "Дистриб'ютор"), ('reseller', 'Реселер'), ('other', 'Інше')], default='b2c', max_length=20, verbose_name='Сегмент'),
        ),
        migrations.AlterField(
            model_name='customernote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
