# Generated by Django 5.2.11 on 2026-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_add_external_key_proper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='external_key',
            field=models.CharField(db_index=True, help_text="Унікальний ідентифікатор для зв'язку з замовленнями", max_length=64, unique=True, verbose_name='Ключ клієнта'),
        ),
    ]
