# Generated by Django 5.2.11 on 2026-04-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_customer_addr_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[('b2b', 'B2B (компанія)'), ('b2c', 'B2C'), ('distributor', "Дистриб'ютор"), ('reseller', 'Реселер'), ('other', 'Інше')], default='b2c', max_length=20, verbose_name='Сегмент'),
        ),
    ]
