# Generated by Django 5.2.11 on 2026-05-04 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customer_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order', '🛒 Замовлення'), ('email_in', '📨 Отримано лист'), ('email_out', '📤 Відправлено лист'), ('ai_analysis', '🏛️ AI аналіз'), ('note', '📝 Нотатка'), ('reminder', '🔔 Нагадування'), ('call', '📞 Дзвінок'), ('meeting', '🤝 Зустріч')], default='note', max_length=20, verbose_name='Тип події')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Деталі')),
                ('ai_summary', models.TextField(blank=True, help_text='Короткий висновок Мінерви', verbose_name='AI резюме')),
                ('related_order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID замовлення')),
                ('related_email_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID email')),
                ('remind_at', models.DateTimeField(blank=True, help_text='Якщо заповнено — Мінерва надішле алерт', null=True, verbose_name='Нагадати о')),
                ('remind_sent', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закріплено вгорі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='crm.customer', verbose_name='Клієнт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Подія клієнта',
                'verbose_name_plural': 'Хронологія клієнта',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='crm_custome_custome_2f644f_idx'), models.Index(fields=['remind_at', 'remind_sent'], name='crm_custome_remind__10f37c_idx')],
            },
        ),
    ]
