# Generated by Django 5.2.11 on 2026-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_customertimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertimeline',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Залиш порожнім — заповниться автоматично (поточний час).', null=True),
        ),
    ]
