# Generated by Django 5.2.11 on 2026-09-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_rfqemailtemplate_diagram_in_body'),
        ('jlcpcb', '0005_jlcconfig_sync_days_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='jlcorder',
            name='file_names',
            field=models.TextField(blank=True, default='', help_text='Імена файлів з усіх позицій замовлення (через \\n). Використовується для пошуку.', verbose_name='Всі файли замовлення'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='auto_receive_on_delivered',
            field=models.BooleanField(default=True, help_text='Автоматично створювати транзакцію Incoming при статусі "Доставлено". Вимкніть для ручного підтвердження через кнопку в адміні.', verbose_name='Авто-прийом на склад при доставці'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='connection_log',
            field=models.TextField(blank=True, default='', help_text='Результат останнього тесту / синхронізації', verbose_name='Лог підключення'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='default_location',
            field=models.CharField(default='MAIN', help_text='Код локації для нових транзакцій прийому (напр. MAIN, WAREHOUSE-A)', max_length=50, verbose_name='Локація складу за замовчуванням'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='notify_email_to',
            field=models.CharField(blank=True, default='', help_text='Порожньо = адреса з загальних налаштувань сповіщень', max_length=500, verbose_name='Email одержувачів (через кому)'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='sync_enabled',
            field=models.BooleanField(default=False, help_text='Автоматично оновлювати статуси замовлень з JLCPCB API', verbose_name='Авто-синхронізація'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='sync_interval_hours',
            field=models.PositiveSmallIntegerField(default=4, help_text='Рекомендовано: 2–8 год', verbose_name='Інтервал (годин)'),
        ),
        migrations.AlterField(
            model_name='jlcconfig',
            name='use_sandbox',
            field=models.BooleanField(default=False, help_text='Тестовий режим (якщо JLCPCB надав sandbox endpoint)', verbose_name='Sandbox режим'),
        ),
        migrations.AlterField(
            model_name='jlcorder',
            name='auto_matched_sku',
            field=models.CharField(blank=True, default='', help_text='SKU знайдений автоматично при матчингу', max_length=255, verbose_name='Авто-знайдений SKU'),
        ),
        migrations.AlterField(
            model_name='jlcorder',
            name='jlc_order_id',
            field=models.CharField(help_text='Унікальний ID з системи JLCPCB', max_length=100, unique=True, verbose_name='ID замовлення JLC'),
        ),
        migrations.AlterField(
            model_name='jlcorder',
            name='jlc_status',
            field=models.CharField(blank=True, default='', help_text='Оригінальний статус від JLCPCB API', max_length=100, verbose_name='Статус JLC (raw)'),
        ),
        migrations.AlterField(
            model_name='jlcorder',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Продукт у каталозі складу, що відповідає цьому замовленню', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jlc_orders', to='inventory.product', verbose_name='Товар на складі'),
        ),
        migrations.AlterField(
            model_name='jlcorder',
            name='tracking_carrier',
            field=models.CharField(blank=True, default='', help_text='DHL, UPS, FedEx тощо', max_length=100, verbose_name='Перевізник'),
        ),
    ]
