# Generated by Django 5.2.11 on 2026-09-05 07:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_rfqemailtemplate_diagram_in_body'),
        ('jlcpcb', '0006_add_file_names_to_jlcorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='JLCOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=500, verbose_name='Файл')),
                ('produce_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Код виробництва')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='К-сть')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна (USD)')),
                ('status_key', models.CharField(blank=True, default='', max_length=30, verbose_name='Статус JLC')),
                ('received_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Отримано (шт)')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата замовлення')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='ETA доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='jlcpcb.jlcorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jlc_lines', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення JLCPCB',
                'verbose_name_plural': 'Позиції замовлень JLCPCB',
                'ordering': ['pk'],
                'unique_together': {('order', 'file_name')},
            },
        ),
    ]
