# Generated by Django 5.2.11 on 2026-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Логін або API Key від платформи', max_length=500, verbose_name='API ключ / логін'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='api_secret',
            field=models.CharField(blank=True, default='', help_text='Пароль або Secret Key', max_length=500, verbose_name='API секрет / пароль'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='api_url',
            field=models.CharField(blank=True, default='', help_text='Базовий URL API (залишити порожнім для стандартного)', max_length=300, verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='sender_country',
            field=models.CharField(blank=True, default='DE', help_text='Двобуквений код: DE, UA, PL, US...', max_length=2, verbose_name='Країна (ISO 2)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier_service',
            field=models.CharField(blank=True, default='', help_text='Наприклад: DHL Express, UPS Standard', max_length=200, verbose_name='Послуга перевізника'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.CharField(blank=True, default='', help_text="Для митниці: напр. 'Electronic components'", max_length=300, verbose_name='Опис вмісту'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient_country',
            field=models.CharField(blank=True, default='', help_text='Двобуквений код: UA, PL, DE, US...', max_length=2, verbose_name='Країна (ISO 2)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Буде надруковано на етикетці', max_length=100, verbose_name='Референс/номер замовлення'),
        ),
    ]
