# Generated by Django 5.2.11 on 2026-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_packagingmaterial_cm_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagingmaterial',
            options={'ordering': ['box_type', 'length_cm', 'width_cm'], 'verbose_name': 'Пакувальний матеріал', 'verbose_name_plural': 'Пакувальні матеріали'},
        ),
    ]
