# Generated by Django 5.2.11 on 2026-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_shipment_customs_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Jumingo: X-AUTH-TOKEN | DHL: API Key | UPS/FedEx: Client ID', max_length=500, verbose_name='API ключ'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='api_secret',
            field=models.CharField(blank=True, default='', help_text='DHL: API Secret | UPS/FedEx: Client Secret | Jumingo: не використовується', max_length=500, verbose_name='API Secret / пароль'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='api_url',
            field=models.CharField(blank=True, default='', help_text='DHL: введи «test» для sandbox. Для інших залишити порожнім.', max_length=300, verbose_name='API URL / режим'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='connection_uuid',
            field=models.CharField(blank=True, default='', help_text='Jumingo: UUID інтеграції | DHL: Account Number (9 цифр) | інші: не використовується', max_length=100, verbose_name='Connection UUID / Account №'),
        ),
    ]
