# Generated by Django 5.2.11 on 2026-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_shippingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='last_tracking_run',
            field=models.DateTimeField(blank=True, help_text='Заповнюється автоматично після кожного успішного запуску.', null=True, verbose_name='Останній запуск'),
        ),
        migrations.AlterField(
            model_name='shippingsettings',
            name='tracking_interval_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Як часто оновлювати трекінг. Cron повинен запускати команду частіше цього інтервалу.', verbose_name='Інтервал оновлення (хвилини)'),
        ),
    ]
