# Generated by Django 5.2.11 on 2026-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0021_drop_upsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='api_url',
            field=models.CharField(blank=True, default='', help_text='DHL: «test» для sandbox | UPS: «sandbox» для sandbox | решта: порожньо = production', max_length=300, verbose_name='API URL / режим'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='connection_uuid',
            field=models.CharField(blank=True, default='', help_text='Jumingo: UUID інтеграції | DHL: Account Number (9 цифр) | UPS: Account Number (6 символів)', max_length=100, verbose_name='Connection UUID / Account №'),
        ),
    ]
