# Generated by Django 5.2.11 on 2026-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0022_carrier_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Місто відправника'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Компанія відправника'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_country',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Країна відправника (ISO 2)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Ім'я відправника"),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон відправника'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_street',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Вулиця відправника'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ZIP відправника'),
        ),
    ]
