# Generated by Django 5.2.11 on 2026-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0023_shipment_sender_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email відправника'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Штат / провінція відправника'),
        ),
    ]
