# Generated by Django 5.2.11 on 2026-04-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0024_shipment_sender_state_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingsettings',
            name='ups_log_max_entries',
            field=models.PositiveSmallIntegerField(default=20, help_text='Скільки останніх UPS API запитів/відповідей зберігати у лог-файлі (1–200).', verbose_name='UPS лог — макс. записів'),
        ),
    ]
