# Generated by Django 5.2.11 on 2026-04-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0026_api_log_max_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customs_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL митної декларації (PDF)'),
        ),
    ]
