# Generated by Django 5.2.11 on 2026-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0028_shipment_carrier_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier_eta',
            field=models.DateField(blank=True, help_text='Дата з тарифу перевізника, заповнюється при бронюванні', null=True, verbose_name='Орієнтовна дата доставки (тариф)'),
        ),
    ]
