# Generated by Django 5.2.11 on 2026-04-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0029_alter_shipment_carrier_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Нотатки'),
        ),
    ]
