# Generated by Django 5.2.11 on 2026-04-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0030_shipment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingsettings',
            name='tracking_log_max_entries',
            field=models.PositiveSmallIntegerField(default=500, help_text='Скільки останніх спроб трекінгу зберігати у базі (100–2000).', verbose_name='Лог трекінгу — макс. записів'),
        ),
        migrations.CreateModel(
            name='TrackingAttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker', models.CharField(max_length=20, verbose_name='Сервіс')),
                ('success', models.BooleanField(verbose_name='Успіх')),
                ('status_found', models.CharField(blank=True, max_length=100, verbose_name='Знайдений статус')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='Час (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_logs', to='shipping.shipment', verbose_name='Відправлення')),
            ],
            options={
                'verbose_name': 'Лог трекінгу',
                'verbose_name_plural': 'Лог трекінгу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(choices=[('jumingo', 'Jumingo (агрегатор)'), ('dhl', 'DHL'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('other', 'Інше')], max_length=20, verbose_name='Тип перевізника')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1=основний, 2=перший fallback, 3=другий fallback', verbose_name='Пріоритет')),
                ('tracker', models.CharField(choices=[('jumingo', 'Jumingo'), ('dhl', 'DHL (MyDHL+ API)'), ('dhl_track', 'DHL Tracking Unified'), ('ups', 'UPS'), ('fedex', 'FedEx')], max_length=20, verbose_name='Сервіс трекінгу')),
                ('enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('interval_override', models.PositiveSmallIntegerField(default=0, verbose_name='Інтервал (хв, 0=глобальний)')),
            ],
            options={
                'verbose_name': 'Правило трекінгу',
                'verbose_name_plural': 'Правила трекінгу',
                'ordering': ['carrier_type', 'priority'],
                'unique_together': {('carrier_type', 'priority')},
            },
        ),
    ]
