# Generated by Django 5.2.11 on 2026-04-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0031_shippingsettings_tracking_log_max_entries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingsettings',
            options={'verbose_name': 'Налаштування', 'verbose_name_plural': 'Налаштування'},
        ),
        migrations.AlterUniqueTogether(
            name='trackingrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_delay_notified',
            field=models.DateField(blank=True, help_text='Дата останнього відправленого Telegram-сповіщення про затримку', null=True, verbose_name='Останнє сповіщення про затримку'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='delay_notify_enabled',
            field=models.BooleanField(default=True, help_text='Вмикає Telegram-сповіщення коли посилка затримується або ETA прострочена.', verbose_name='Сповіщення про затримки'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='delay_notify_frequency',
            field=models.CharField(choices=[('once', 'Один раз (при першому виявленні)'), ('daily', 'Щодня (поки затримка не усунена)'), ('every_sync', 'Кожен раз при синхронізації')], default='once', help_text='Як часто надсилати Telegram-сповіщення про одну і ту ж затриману посилку.', max_length=20, verbose_name='Частота сповіщень про затримки'),
        ),
        migrations.AddField(
            model_name='trackingrule',
            name='tracking_number_prefix',
            field=models.CharField(blank=True, default='', help_text='Якщо вказано — правило застосовується ТІЛЬКИ для трекінг-номерів з цим префіксом. Приклади: 1Z (UPS), JD (DHL Paket), 7489 (DHL Express). Порожньо = матчить за типом перевізника.', max_length=20, verbose_name='Префікс трекінг-номера'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingrule',
            unique_together={('carrier_type', 'priority', 'tracking_number_prefix')},
        ),
    ]
