# Generated by Django 5.2.11 on 2026-04-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0032_trackingrule_prefix_delay_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Фактична дата і час доставки від API перевізника', null=True, verbose_name='Фактична дата доставки'),
        ),
    ]
