# Generated by Django 5.2.11 on 2026-04-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_salessettings_dymo_open_mode'),
        ('shipping', '0034_carrier_sender_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorder', verbose_name='Замовлення'),
        ),
    ]
