# Generated by Django 5.2.11 on 2026-04-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0035_shipment_order_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('company', models.CharField(blank=True, default='', max_length=150, verbose_name='Компанія')),
                ('category', models.CharField(choices=[('client', 'Клієнт'), ('supplier', 'Постачальник'), ('sender', 'Відправник (склад)'), ('warehouse', 'Склад/партнер'), ('other', 'Інше')], default='client', max_length=20, verbose_name='Категорія')),
                ('is_sender', models.BooleanField(default=False, help_text='Позначити як типового відправника', verbose_name='Відправник')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Телефон')),
                ('addr_street', models.CharField(blank=True, default='', max_length=200, verbose_name='Вулиця, будинок')),
                ('addr_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Місто')),
                ('addr_zip', models.CharField(blank=True, default='', max_length=20, verbose_name='Поштовий індекс')),
                ('addr_state', models.CharField(blank=True, default='', max_length=100, verbose_name='Штат / провінція')),
                ('addr_country', models.CharField(blank=True, default='', max_length=2, verbose_name='Країна (ISO 2)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Нотатки')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Використань')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адресна книга',
                'ordering': ['-use_count', 'name'],
            },
        ),
    ]
