# Generated by Django 5.2.11 on 2026-04-30 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0036_addressbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Порожньо = спільний запис (видно всім); вказано = особистий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_book_entries', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
    ]
