# Generated by Django 5.2.11 on 2026-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0040_shippingsettings_status_conflict_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingsettings',
            name='status_conflict_priority',
            field=models.CharField(choices=[('highest', 'Вищий статус — найбільш просунутий (поточна поведінка)'), ('carrier', 'Перевізник (UPS/DHL) — якщо відправлення активне, не ставити «Доставлено» з маркетплейсу'), ('marketplace', 'Маркетплейс (DigiKey) — завжди вірити статусу замовлення')], default='highest', help_text='Що робити якщо різні джерела показують різний статус. Наприклад: DigiKey каже «Доставлено», а UPS — «В дорозі».<br><b>Вищий статус</b> — беремо найбільш просунутий (DigiKey виграє).<br><b>Перевізник</b> — поки відправлення активне (UPS/DHL не delivered), маркетплейс не може встановити «Доставлено».<br><b>Маркетплейс</b> — статус DigiKey/маркетплейсу завжди в пріоритеті.', max_length=20, verbose_name='Пріоритет при конфлікті статусів'),
        ),
    ]
