# Generated by Django 5.2.11 on 2026-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0042_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list, verbose_name='Позиції'),
        ),
    ]
