# Generated by Django 5.2.11 on 2026-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0043_invoice_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Файл .pdf'),
        ),
    ]
