# Generated by Django 5.2.11 on 2026-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0044_invoice_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipped_to_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Адреса отримувача (повна)'),
        ),
    ]
