# Generated by Django 5.2.11 on 2026-09-14 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlcpcb', '0007_add_jlcorderline'),
        ('shipping', '0045_invoice_shipped_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='jlc_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='jlcpcb.jlcorder', verbose_name='JLCPCB замовлення'),
        ),
    ]
