# Generated by Django 5.2.11 on 2026-10-01 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_salesorderline_total_price'),
        ('shipping', '0051_shipment_ups_payer_addresses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=30, verbose_name='Номер')),
                ('pl_date', models.DateField(verbose_name='Дата')),
                ('ship_to', models.JSONField(blank=True, default=dict, verbose_name='Отримувач')),
                ('parcels', models.JSONField(blank=True, default=list, verbose_name='Коробки')),
                ('signer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Підписант')),
                ('signer_position', models.CharField(blank=True, default='', max_length=120, verbose_name='Посада')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='packing_lists/', verbose_name='Файл .docx')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='packing_lists/', verbose_name='Файл .pdf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_lists', to='sales.salesorder', verbose_name='Замовлення')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_lists', to='shipping.shipment', verbose_name='Відправлення')),
            ],
            options={
                'verbose_name': 'Пакувальний лист',
                'verbose_name_plural': 'Пакувальні листи',
                'ordering': ['-created_at'],
            },
        ),
    ]
