# Generated by Django 5.2.11 on 2026-10-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_salesorderline_total_price'),
        ('shipping', '0052_packinglist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=30, verbose_name='Номер')),
                ('inv_date', models.DateField(verbose_name='Дата')),
                ('ship_to', models.JSONField(blank=True, default=dict, verbose_name='Отримувач')),
                ('billing_address', models.TextField(blank=True, default='', verbose_name='Billing address')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('lines', models.JSONField(blank=True, default=list, verbose_name='Позиції')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Пакування і доставка')),
                ('incoterm', models.CharField(blank=True, default='DAP', max_length=10, verbose_name='Incoterm')),
                ('export_reason', models.CharField(blank=True, default='commercial sale', max_length=100, verbose_name='Reason of export')),
                ('payment_terms', models.CharField(blank=True, default='advance payment.', max_length=200, verbose_name='Payment terms')),
                ('signer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Підписант')),
                ('signer_position', models.CharField(blank=True, default='', max_length=120, verbose_name='Посада')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='commercial_invoices/', verbose_name='Файл .docx')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='commercial_invoices/', verbose_name='Файл .pdf')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_invoices', to='sales.salesorder', verbose_name='Замовлення')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_invoices', to='shipping.shipment', verbose_name='Відправлення')),
            ],
            options={
                'verbose_name': 'Комерційний інвойс',
                'verbose_name_plural': 'Комерційні інвойси',
                'ordering': ['-created_at'],
            },
        ),
    ]
