# Generated by Django 5.2.11 on 2026-10-05 12:22

import shipping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0053_commercialinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shop_confirm_dismissed',
            field=models.BooleanField(default=False, help_text='Банер «Підтвердити відправлення» відхилено для цього відправлення.', verbose_name='Не пропонувати підтвердження в магазині'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='shop_confirm_prompt',
            field=models.BooleanField(default=True, help_text='На сторінці відправлення з етикеткою/трекінгом показувати банер «Підтвердити відправлення», поки замовлення не позначене як відправлене.', verbose_name='Пропонувати підтвердити відправлення в магазині'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='shop_confirm_sources',
            field=models.JSONField(blank=True, default=shipping.models.default_shop_confirm_sources, help_text='DigiKey — підтвердження через DigiKey API (автоматично або вручну). Інші — замовлення позначається як «Відправлено» в Minerva.', verbose_name='Для яких джерел (магазинів)'),
        ),
    ]
