# Generated by Django 5.2.11 on 2026-03-02 13:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_companysettings_logo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='accounting__status_3055e0_idx',
            old_name='accounting_invoice_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='accounting__issue_d_72488a_idx',
            old_name='accounting_invoice_issue_date_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='accounting__due_dat_cfd46e_idx',
            old_name='accounting_invoice_due_date_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0, 7, 19, 20 — залежно від країни/типу послуги', max_digits=5, verbose_name='VAT %'),
        ),
    ]
