# Generated by Django 5.2.11 on 2026-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_companysettings_invoice_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон (Tel)'),
        ),
    ]
