# Generated by Django 5.2.10 on 2026-02-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='digikey', max_length=32)),
                ('order_number', models.CharField(max_length=64)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_region', models.CharField(blank=True, default='', max_length=64)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('source', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_raw', models.CharField(blank=True, default='', max_length=128)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
