# Generated by Django 5.2.10 on 2026-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_customer_salesorder_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='client',
            new_name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('source', 'order_number')},
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_region',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='source',
            field=models.CharField(default='digikey', max_length=32),
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='affects_stock',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_courier',
        ),
    ]
