# Generated by Django 5.2.10 on 2026-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_client_salesorder_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='customer',
            new_name='client',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='affects_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='document_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SAMPLE', 'Sample'), ('TRANSFER', 'Transfer'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='SALE', max_length=16),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='lieferschein_nr',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_courier',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_region',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
