# Generated by Django 5.2.11 on 2026-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_customer_salesorder_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='affects_stock',
            field=models.BooleanField(default=True, help_text='Чи впливає це замовлення на залишки на складі'),
        ),
    ]
