# Generated by Django 5.2.11 on 2026-02-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_id_alter_customer_segment_and_more'),
        ('inventory', '0013_alter_product_unit_type_and_more'),
        ('sales', '0005_alter_salesorder_affects_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='crm.customer', verbose_name='Клієнт CRM'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='affects_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
