# Generated by Django 5.2.11 on 2026-02-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_unit_type_and_more'),
        ('sales', '0006_salesorder_customer_salesorderline_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date'], 'verbose_name': 'Продаж', 'verbose_name_plural': 'Продажі'},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'verbose_name': 'Позиція продажу', 'verbose_name_plural': 'Позиції продажів'},
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='affects_stock',
            field=models.BooleanField(default=True, verbose_name='Впливає на склад'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='document_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SAMPLE', 'Sample'), ('TRANSFER', 'Transfer'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='SALE', max_length=16, verbose_name='Тип документу'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='lieferschein_nr',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Lieferschein-Nr'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата замовлення'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=64, verbose_name='№ замовлення'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата відправки'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_address',
            field=models.TextField(blank=True, default='', verbose_name='Адреса доставки'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_courier',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name="Кур'єр"),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline відправки'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_region',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='source',
            field=models.CharField(default='digikey', max_length=32, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Tracking'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='sku_raw',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='SKU (raw)'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Ціна за од.'),
        ),
    ]
