# Generated by Django 5.2.11 on 2026-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('received', 'Отримано'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('cancelled', 'Скасовано')], default='received', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата замовлення'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipped_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відправки'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='source',
            field=models.CharField(choices=[('digikey', 'DigiKey'), ('nova_post', 'Нова Пошта'), ('other', 'Інші'), ('webshop', 'Webshop')], default='digikey', max_length=32, verbose_name='Джерело'),
        ),
    ]
