# Generated by Django 5.2.11 on 2026-02-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_reorderproxy'),
        ('sales', '0013_add_contact_name_fixed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість доставки'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='affects_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='document_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SAMPLE', 'Sample'), ('TRANSFER', 'Transfer'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='SALE', max_length=16),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='lieferschein_nr',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipped_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_courier',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipping_region',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='source',
            field=models.CharField(default='digikey', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('received', 'Отримано'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('cancelled', 'Скасовано')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='sku_raw',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
