# Generated by Django 5.2.11 on 2026-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Посилання на Customer.external_key', max_length=64, verbose_name='Ключ клієнта CRM'),
        ),
    ]
