# Generated by Django 5.2.11 on 2026-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_migrate_salesorder_addresses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='sales_sales_order_d_55e46c_idx',
            old_name='sales_order_date_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='sales_sales_status_480214_idx',
            old_name='sales_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='sales_sales_source_98c394_idx',
            old_name='sales_source_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='sales_sales_addr_co_abb23a_idx',
            old_name='sales_addr_country_idx',
        ),
        migrations.AlterField(
            model_name='salessource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salessource',
            name='slug',
            field=models.CharField(help_text='Латиниця, без пробілів. Зберігається в замовленнях.', max_length=32, unique=True, verbose_name='Код (slug)'),
        ),
    ]
