# Generated by Django 5.2.11 on 2026-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_salesorder_addr_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('received', 'Отримано'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='received', max_length=20),
        ),
    ]
