# Generated by Django 5.2.11 on 2026-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактична доставка'),
        ),
    ]
