# Generated by Django 5.2.11 on 2026-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_fix_source_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_docs_path', models.CharField(blank=True, default='', help_text='Основна директорія на ПК куди копіювати документи. Приклад: C:\\Users\\name\\Documents\\Orders', max_length=500, verbose_name='Шлях для локального збереження')),
                ('local_save_enabled', models.BooleanField(default=False, help_text='Якщо ввімкнено і вказано шлях — документи автоматично копіюються на ПК при завантаженні та генерації.', verbose_name='Зберігати копії локально')),
                ('auto_save_to_server', models.BooleanField(default=True, help_text='При натисканні 💾 на Пакувальному листі / Proforma / Митній декларації зберігати PDF на сервер (без зайвого підтвердження).', verbose_name='Автоматично зберігати PDF на сервер')),
            ],
            options={
                'verbose_name': 'Налаштування',
                'verbose_name_plural': 'Налаштування',
            },
        ),
    ]
