# Generated by Django 5.2.11 on 2026-04-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_salessettings_auto_save_labels_to_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='internal_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Нотатка'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='⭐ Важливе'),
        ),
    ]
