# Generated by Django 5.2.11 on 2026-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_flag_and_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='show_product_image_tooltip',
            field=models.BooleanField(default=True, help_text='У списку замовлень при наведенні на Артикул показує фото товару зі складу. Вимкніть якщо це сповільнює роботу.', verbose_name='Показувати фото товару при наведенні'),
        ),
    ]
