# Generated by Django 5.2.11 on 2026-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_salessettings_show_pdf_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='label_open_mode',
            field=models.CharField(choices=[('view', '🔗 Відкрити в новій вкладці браузера'), ('download', '⬇️ Завантажити файл'), ('ask', '❓ Запитувати щоразу')], default='view', help_text='Що робити при натисканні PDF-лінку мітки UPS/DHL у списку замовлень. Якщо браузер не може відкрити PDF — автоматично завантажується.', max_length=16, verbose_name='Дія при натисканні на мітку перевізника (PDF)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='internal_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Нотатка'),
        ),
    ]
