# Generated by Django 5.2.11 on 2026-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_salessettings_label_open_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='dymo_open_mode',
            field=models.CharField(choices=[('download', '⬇️ Завантажити .dymo файл'), ('print', '🖨️ Надрукувати через DYMO Label Software (localhost)'), ('ask', '❓ Запитувати щоразу')], default='download', help_text='«Завантажити» — зберігає .dymo файл у Downloads; «Через DYMO» — надсилає на принтер через DYMO Label Software (localhost:41951) — програма має бути встановлена і запущена; «Запитувати» — показує діалог вибору щоразу.', max_length=16, verbose_name='Дія при натисканні 🖨️ Друкувати (DYMO мітка)'),
        ),
    ]
