# Generated by Django 5.2.11 on 2026-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_salessettings_dymo_open_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='ship_company',
            field=models.CharField(blank=True, default='', help_text='Якщо порожньо — береться з «Client».', max_length=255, verbose_name='Компанія отримувача'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_email',
            field=models.EmailField(blank=True, default='', help_text='Якщо порожньо — береться з «Email».', max_length=254, verbose_name='Email доставки'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_name',
            field=models.CharField(blank=True, default='', help_text='Особа, яка отримує посилку. Якщо порожньо — береться з «Контактна особа».', max_length=255, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_phone',
            field=models.CharField(blank=True, default='', help_text='Якщо порожньо — береться з «Phone».', max_length=64, verbose_name='Телефон доставки'),
        ),
    ]
