# Generated by Django 5.2.11 on 2026-06-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_salesorder_order_confirm_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderline',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
