# Generated by Django 5.2.11 on 2026-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_salesorderline_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', '—'), ('invoice', 'Рахунок (Rechnung)'), ('prepayment', 'Передоплата (Vorkasse)'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Інше')], default='', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='ID транзакції PayPal/Stripe або призначення платежу', max_length=128, verbose_name='Референс оплати'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('unpaid', 'Не оплачено'), ('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('refunded', 'Повернено'), ('failed', 'Помилка оплати')], db_index=True, default='', max_length=20, verbose_name='Статус оплати'),
        ),
    ]
