# Generated by Django 5.2.11 on 2026-10-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_shop_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='document_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SAMPLE', 'Sample'), ('TRANSFER', 'Transfer'), ('WARRANTY', 'Warranty'), ('QUOTE', 'Запит пропозиції'), ('OTHER', 'Other')], default='SALE', max_length=16),
        ),
    ]
